#!/bin/sh

MAX_VOL=250
NOTIF_ID=123

notify() {
    res=$(dunstify         \
              -r $NOTIF_ID \
              -A 'gui,GUI' \
              "$@")
    if [ "$res" = gui ]; then
        pavucontrol
    fi
}

vol_notif() {
    V="$1"
    [ "$V" ] || V=$(pamixer --get-volume)
	if [ "$(pamixer --get-mute)" = "true" ]; then
        notify "Volume: Muted"
	else
        notify -h int:value:"$V" "Volume: $V%"
    fi
}

mic_notif() {
    if amixer sget Capture | grep -Eq 'Capture.+\[on\]'; then
        notify "Microphone: ON"
    else
        notify "Microphone: OFF"
    fi
}

vol() {
    [ "$1" ] || return 1
    LOCK='/tmp/__audioctl_vol_lock'
    [ -f "$LOCK" ] && return
    touch "$LOCK"
    C="$1"
    D="$2"; [ "$D" ] || D=5
    case "$C" in
        m) pamixer -m ;;
        t) pamixer -t ;;
        up|down)
            [ "$C" = down ] && D="-$D"
            V=$(pamixer --get-volume)
            V=$((V+D))
            if [ $V -le $MAX_VOL ]; then
                V=$((V/5*5))
            else
                V=$MAX_VOL
            fi
            if [ $V -lt 0 ]; then
                V=0
            fi
            pamixer --allow-boost --set-volume $V
            ;;
    esac
    rm -f "$LOCK"
	vol_notif "$V"
}

vol1() {
    C="$1"
    D="$2"; [ "$D" ] || D=5
    case "$C" in
        t)    amixer -q set Master toggle ;;
        m)    amixer -q set Master mute   ;;
        up)   amixer -q set Master "$D%+" ;;
        down) amixer -q set Master "$D%-" ;;
    esac
	vol_notif
}

V="$2"
case "$1" in
	"up")       vol up   "$V"                                 ;;
	"down")     vol down "$V"                                 ;;
	"mute")     amixer -q set Master toggle;  vol_notif       ;;
	"mutemic")  amixer -q set Capture toggle; mic_notif       ;;
	"stop")     mpc -q stop       || cmus-remote --stop       ;;
	"pause")    mpc -q toggle     || cmus-remote --pause      ;;
	"forward")  mpc -q seek +"$V" || cmus-remote --seek +"$V" ;;
	"back")     mpc -q seek -"$V" || cmus-remote --seek -"$V" ;;
	"next")     mpc -q next       || cmus-remote --next       ;;
	"prev")     mpc -q prev       || cmus-remote --prev       ;;
	"replay")   mpc seek 0%       || cmus-remote --seek 0     ;;
    "gui")      pavucontrol ;;
esac
