#!/bin/sh

D="$HOME/.screenlayout"

OPTS='Auto
Mirror
Extend
Edit screen layout
Invert colors
Temperature: 6500  Default
Temperature: 5000  Warm
Temperature: 9000  Cool
Temperature: 2000  Extra Warm
Temperature: 20000 Extra Cool
Temperature: Custom'

list() {
    echo "$OPTS"
    # find "$D" -type f -exec basename '{}' \; |
    #     grep -v '^default' |
    #     awk -F'.' '{print $1}'
}

if [ "$1" = '-d' ]; then
    sel='Auto'
else
    l=$(list)
    l_len=$(echo "$l" | wc -l)
    [ "$l_len" -gt 20 ] && l_len=20
    sel=$(echo "$l" | menus-face -i -l "$l_len" -p 'Display options')
fi

case "$sel" in
    '') ;;

    Auto)
        automon auto ;;

    Mirror)
        automon mirror ;;

    Extend)
        automon extend ;;

    Edit*)
        arandr ;;

    Invert*)
        xrandr-invert-colors ;;

    Temperature*)
        sel=$(echo "$sel" | awk '{print $2}')
        if [ "$sel" = Custom ]; then
            sel=$(echo | menus-face -p 'Color temperature')
        fi
        [ "$sel" ] && xsct "$sel" ;;

    *)
        sh "$D/${sel}.sh" ;;
esac

setwallpaper
