#!/bin/sh

LANGS=us,ar
LANGS_E=us,ar,ru,fr,de,ir

# grep "grp:.*toggle" /usr/share/X11/xkb/rules/base.lst
KEYS=win_space_toggle

langget() {
    setxkbmap -query | sed -En 's/layout:\s*(.+)/\1/p' 2>/dev/null
}

langinit() {
    langs="$1"
    [ -n "$langs" ] || langs=$LANGS
    [ "$1" = '-e' ] && langs=$LANGS_E
    setxkbmap -layout $langs -option grp:$KEYS
    [ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
}

langtog() {
    : # TODO: ???
}

main() {
    case "$1" in
        us)    langinit us; langinit ;;
        init)  shift; langinit "$@"  ;;
        'tog') shift; langtog        ;;
        '')           langget        ;;
    esac
}

main "$@"
