#!/bin/sh

handle() {
    usermodmap=$HOME/.Xmodmap
    if [ -f "$usermodmap" ]; then
        xmodmap "$usermodmap"
    fi

    xset r rate 230 50
}

main() {
    handle
    if [ "$1" = daemon ]; then
        udevadm monitor | while read -r line; do
            if echo "$line" | grep -Eq 'UDEV.+\(input\)'; then
                date
                echo "$line"
                handle
            fi
        done
    fi
}

main "$@"

# synclient \
#     VertScrollDelta=-500 \
#     HorizScrollDelta=-500 \
#     TapButton1=1 \
#     TapButton2=3 \
#     TapButton3=2 \
#     MinSpeed=1.5 \
#     MaxSpeed=7 \
#     AccelFactor=0.1 \
#     HorizTwoFingerScroll=1 \
#     VertTwoFingerScroll=1 \
#     PalmDetect=1
