#!/bin/sh

# https://wiki.archlinux.org/title/Webcam_setup

last=$(command ls -1 /dev/video* |
           tail -n1 |
           sed -rn 's@/dev/video([0-9]+)@\1@p')

if [ "$last" = 1 ]; then
    dev=/dev/video0
else
    dev=$(seq 0 2 "$last" | tac |
              xargs printf '/dev/video%s\n' |
              menus-face -l $(((last / 2) + 1)))
fi

[ -e "$dev" ] || exit 1

pkill -f /dev/video ||
    mpv --no-osc                             \
        --no-input-default-bindings          \
        --input-conf=/dev/null               \
        --geometry=-10-10                    \
        --autofit=15%                        \
        --profile=low-latency                \
        --untimed                            \
        --title='Camera'                     \
        --x11-name='__floatme__|__stickme__' \
        av://v4l2:"$dev"
