#!/bin/sh

O=/usr/share/hwdata/oui.txt
[ -f $O ] || {
    echo "Downloading $O... sudo:"
    sudo download-ouis
}

half=$(echo "$1" | sed 's/\://g' | cut -c1-6)
grep -i "$half" "$O" | tr "\t" "\n" | tail -n1
