#!/bin/sh

isint() { [ "$1" -eq "$1" ] 2>/dev/null; }

l=10
if [ "$1" = '-l' ] && isint "$2"; then
    l="$2"
fi

# https://unix.stackexchange.com/a/230676/183147
LC_ALL=C tr -dc 'A-Za-z0-9!#$%&*+,-./:;<=>@[\]^_{|}' </dev/urandom |
    head -c "$l"
echo
