#!/bin/sh

jail="$HOME/.local/share/jail-android-studio"

do_jail() {
    exec firejail          \
         --noprofile       \
         --private-tmp     \
         --disable-mnt     \
         --private="$jail" \
         "$@"
}

enter_shell() {
    export ANDROID_HOME="$HOME/Android/Sdk"
    export JAVA_HOME='/usr/lib/jvm/default'
    export PATH="$PATH:$HOME/flutter/bin"
    echo "Entering Android jail at $jail..."
    if command -v zsh >/dev/null && [ -f ~/.zshrc ]; then
        cp "$(realpath ~/.zshrc)" "$jail/.zshrc"
        do_jail zsh
    else
        do_jail "$SHELL"
    fi
}

main() {
    targz="$1"
    [ -n "$targz" ] && targz=$(realpath "$targz")

    [ "$1" = 'rm' ]               && { rm -r "$jail"; exit; }
    [ -d "$jail" ]                || mkdir -p "$jail"
    [ -d "$jail/android-studio" ] || {
        mkdir -p "$jail" &&
            cd "$jail"   &&
            if [ -z "$targz" ]; then
                echo 'ERROR: pass the tar.gz file to install'
                echo 'download from: https://developer.android.com/studio#downloads'
                echo 'and flutter from: https://docs.flutter.dev/get-started/install/linux'
                return 1
            else
                tar xvf "$targz"
            fi
    }

    user_desktop="$HOME/.local/share/applications/android-studio.desktop"
    [ -f "$user_desktop" ] || {
        me=$(realpath "$0")
        mkdir -p "$(dirname "$user_desktop")" && {
            echo '[Desktop Entry]'
            echo "Type=Application"
            echo "Name=Android Studio"
            echo "Icon=$jail/android-studio/bin/studio.svg"
            echo "Exec=$me %f"
            echo "Comment=The Drive to Develop"
            echo "Categories=Development;IDE;"
        } > "$user_desktop"
    }

    case "$1" in
        shell)
        enter_shell ;;

        path)
            echo "$jail" ;;

        --help|-h)
            echo "$(basename "$(realpath "$0")"): [shell|path] [ARGS]..." ;;

        *)
            do_jail "$HOME/android-studio/bin/studio.sh" "$@"
    esac
}

main "$@"
