#!/bin/sh

# https://bbs.archlinux.org/viewtopic.php?id=270617
# After updating the system, about a month ago, /dev/ttyUSB0 for the CH340 device ceased to be created. Today I started to figure it out and found out that the brltty package is to blame, or rather the udev rule 90-brltty-device.rules in which 1A86:7523 is present.
# 
# cp /usr/lib/udev/rules.d/90-brltty-device.rules /etc/udev/rules.d/90-brltty-device.rules
# and commenting /etc/udev/rules.d/90-brltty-device.rules
# 
# # Device: 1A86:7523
# # Baum [NLS eReader Zoomax (20 cells)]
# #ENV{PRODUCT}=="1a86/7523/*", ENV{BRLTTY_BRAILLE_DRIVER}="bm", GOTO="brltty_usb_run"
# 
# so that in the future the problem does not appear, you need to fix 90-brltty-device.rules at brltty

echo 'COMPILING...'
arduino-cli compile --fqbn arduino:avr:nano && {
    echo 'BUILD SUCCESS!'
    device=$(ls /dev/ttyUSB* 2>/dev/null | head -n1)
    [ -z "$device" ] &&
        device=$(ls /dev/ttyACM* 2>/dev/null | head -n1)
    [ -z "$device" ] && {
        echo 'No device found'
        exit 1
    }
    echo "UPLOADING to $device"
    arduino-cli upload --fqbn arduino:avr:nano -p "$device" ||
        sudo arduino-cli upload --fqbn arduino:avr:nano -p "$device"
}

# `arduino-cli.yaml`:
# board_manager:
#   additional_urls:
#     - https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
#     - http://arduino.esp8266.com/stable/package_esp8266com_index.json
#     - http://digistump.com/package_digistump_index.json
