#!/bin/sh

# Tiny interface to emacs

#BIDI=1

BINPATH=$(realpath "$0")

export TERM='screen-256color'

daemon() { emacsclient -e 0 >/dev/null || emacs --daemon "$@"; }
die()    { exec emacsclient -e '(kill-emacs)'; }
client() { daemon; emacsclient "$@"; }

gui() { client -c "$@"; }
existing() { client -n "$@"; }
tnw() { exec theterm "$BINPATH" nw "$@"; }
nw()  {
    tmux set automatic-rename off
    client -nw "$@"
    tmux set automatic-rename on
}

[ "$BIDI" ] &&
    nw() { exec bicon.bin --reshape-only "$BINPATH" c -nw "$@" 2>/dev/null; }

command -v emacs >/dev/null || {
    # emacs is not installed, assume nano is
    daemon() { :; }
    die()    { :; }
    client() { exec nano "$@"; }

    tnw() { exec theterm "$BINPATH" nw "$@"; }
    gui() { tnw "$@"; }
    existing() { gui "$@"; }
    nw()  { client "$@"; }
}

main() {
    CMD="$1"
    case "$CMD" in
        d|daemon)   shift && daemon   "$@";;
        k|kill|die)          die          ;;
        c|client)   shift && client   "$@";;
        e|existing) shift && existing "$@";;
        g|gui)      shift && gui      "$@";;
        n|nw)       shift && nw       "$@";;
        t|tnw)      shift && tnw      "$@";;
        *)
            if [ "$EMACS_VTERM_PATH" ]; then
                existing "$@"
            elif [ -t 0 ]; then
                nw "$@"
            else
                gui "$@"
            fi;;
    esac
}

main "$@"
