#!/bin/sh

# https://developer.android.com/studio#downloads
# https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.1.1.21/android-studio-2021.1.1.21-linux.tar.gz
exec ~/.local/share/android/android-studio/bin/studio.sh "$@"
