#!/bin/sh

# TODO: move to personal

WORDS="¯\\_(ツ)_/¯
السلام عليكم
السلام عليكم و رحمة الله و بركاته
و عليكم السلام و رحمة الله و بركاته
Alsalamu alykum
Wa alykum alsalam
naheelazawy@gmail.com
nk1508530@qu.edu.qa
(☞ﾟヮﾟ)☞ ☜(ﾟヮﾟ☜)
(☞ﾟ∀ﾟ)☞
◔ ⌣ ◔
( ͡° ͜ʖ ͡°)
( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)"

R=$(echo "$WORDS" | ndg menu -d -p 'Words')
[ "$R" != '' ] && {
    sleep .1
    xdotool type "$R"
}
