#!/bin/sh

# TODO: move to personal

CTL="$HOME/.data/Public/ctl.sh"

case "$1" in
    -u) "$CTL" end ;;
    -m) "$CTL" begin ;;
    '')
        theterm \
            -a '-f -d 40x5' \
            "echo;echo;exec '$0' -m"
        ;;
esac
