#!/bin/sh

AGENT='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.26 Safari/537.36'
exec chromium --user-agent="$AGENT" --app=https://web.telegram.org/z
