#!/bin/sh

TOS_DIR="$HOME/.local/share/tos"

RC='
// https://gitlab.com/tsoding/aoc-2021

public CBGR48 gr_palette_my[COLORS_NUM]={
  0xffffffffffff, // BLACK
  0x454585858888, // BLUE
  0x989897971a1a, // GREEN
  0x68689d9d6a6a, // CYAN
  0xcccc24241d1d, // RED
  0xb1b162628686, // PURPLE
  0xfefe80801919, // BROWN
  0x3c3c38383636, // LTGRAY
  0x505049494545, // DKGRAY
  0x8383a5a59898, // LTBLUE
  0xb8b8bbbb2626, // LTGREEN
  0x8e8ec0c07c7c, // LTCYAN
  0xfbfb49493434, // LTRED
  0xd3d386869b9b, // LTPURPLE
  0xfafabdbd2f2f, // YELLOW
  0x000000000000  // WHITE
};

GrPaletteSet(gr_palette_my);

// NOTE: for whatever reason when you Abort&Exit (Shift+Esc)
// a User Task (usually a terminal) the theme may reset to
// gr_palette_std. I could not figure out why and how to fix that.
// So I just made gr_palette_std to be gr_palette_gruv.
MemCpy(gr_palette_std, gr_palette_gruv, sizeof(gr_palette_my));
'

cfg() {
    [ -d "$TOS_DIR" ] || {
        echo 'TOS directory does not exist'
        return 1
    }
    cd "$TOS_DIR/EXODUS"                                 &&
        cp -r T ../                                      &&
        mkdir -p ../T/Home                               &&
        printf '%s' "$RC" > ../T/Home/HomeSys.HC         &&
        printf '#include "/Home/HomeSys.HC"\n' >> ../T/Once.HC
}

mk() {
    [ -d "$TOS_DIR" ] && {
        echo 'TOS directory already exists'
        return 1
    }
    mkdir -p "$TOS_DIR"                                  &&
        cd "$TOS_DIR"                                    &&
        git clone https://github.com/1fishe2fishe/EXODUS &&
        cd EXODUS                                        &&
        mkdir build && cd build && cmake .. && make      &&
        cfg
}

gui() {
    cd "$TOS_DIR/EXODUS" &&
        ./exodus -t ../T "$@"
}

cli() {
    gui -c "$@"
}

play() {
    s=$(echo "$@" | sed 's/ //g')
    [ -n "$s" ] || {
        echo 'No music'
        return 1
    }
    printf 'Play("%s");Exit;' "$s" | cli
}

risen() {
    t=${1:-2}
    for _ in $(seq "$t"); do
        play                             \
             5eDEqFFetEEFqDeCDDEetCGF    \
             5eDEqFFetEEFqDeCDDEetCGF    \
             5eDCqDE4eAA5etEEFEDG4B5DCqF \
             5eDCqDE4eAA5etEEFEDG4B5DCqF
    done
}

list() {
    echo cli
    echo gui
    echo play
    echo risen
}

main() {
    [ -d "$TOS_DIR" ] || mk
    cmd="$1"
    if [ $# = 0 ]; then
        cli "$@"
    elif list | grep -q "^$cmd\$"; then
        "$cmd" "$@"
    else
        echo "Unknown command '$cmd'; choose one of:"
        list
        return 1
    fi
}

main "$@"
