#!/bin/sh

main() {
    jail="$HOME/.local/share/jail-zoom"
    version=5.12.6.173
    pac='zoom_x86_64.pkg.tar.xz'
    url="https://cdn.zoom.us/prod/$version/$pac"

    [ "$1" = 'rm' ]     && { rm -r "$jail"; exit; }
    [ -d "$jail" ]      || mkdir -p "$jail"
    [ -f "$jail/$pac" ] || (cd "$jail" && wget "$url")
    [ -d "$jail/zoom" ] || (mkdir -p "$jail/zoom" &&
                                cd "$jail/zoom"   &&
                                tar xvf "$jail/$pac")
    [ -d "$jail/.local/share" ] || {
        desktop="$jail/.local/share/applications/Zoom.desktop"
        mkdir -p "$jail/.local/share" &&
            cp -r "$jail/zoom/usr/share/"* "$jail/.local/share/" &&
            sed -i "s#/usr/bin/zoom#$HOME/zoom/opt/zoom/ZoomLauncher#" \
                "$desktop"
        {
            echo '[MIME Cache]'
            sed -rn 's/MimeType=(.+)/\1/p' "$desktop" |
                tr ';' '\n' |
                xargs printf '%s=Zoom.desktop\n'
        } > "$jail/.local/share/applications/mimeinfo.cache"

    }

    exec firejail          \
         --noprofile       \
         --private-tmp     \
         --blacklist=/mnt  \
         --private="$jail" \
         "$HOME/zoom/opt/zoom/ZoomLauncher"
}

main "$@"
