board_manager:
  additional_urls:
    - https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
    - http://arduino.esp8266.com/stable/package_esp8266com_index.json
    - http://digistump.com/package_digistump_index.json
