#!/bin/sh

xsetroot -cursor_name left_ptr

# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_monitor true

# borderless single window (auto monocle enabler)
# https://github.com/baskerville/bspwm/issues/617
bspc config single_monocle true
bspc config borderless_monocle true

this=$(realpath "$0")
bspc config external_rules_command "${this}-rules"

bspdd daemon &
