#!/bin/sh

bspc monitor      -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-1 -d 10 2>/dev/null

bspc config border_width         2
bspc config window_gap           0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# looks like regex doesn't work here. TODO: fix
# bspc rule -a '.*__floatme__.*' state=floating
# bspc rule -a '.*__stickme__.*' sticky=on
# bspc rule -a 'dragon'          sticky=on
