#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xdotool getwindowname "$wid")

case "$class" in
    Dragon)
        echo 'sticky=on' ;;
    Emacs)
        echo 'state=tiled' ;;
    Empty)
        echo 'state=tiled' ;;
    dmenu|Pavucontrol|Arandr|Onboard|\
        Panther_launcher)
        echo 'state=floating' ;;
esac

case "$instance" in
    *__floatme__*)
        echo 'state=floating' ;;
esac

case "$title" in
    *__floatme__* | \
        'Python Turtle Graphics' | \
        'Picture in picture')
        echo 'state=floating' ;;
esac

case "$title" in
    *__stickme__*)
        echo 'sticky=on' ;;
esac

case "$class" in
    *__floatme__*)
        echo 'state=floating' ;;
esac

case "$class" in
    *__stickme__*)
        echo 'sticky=on' ;;
esac

# https://github.com/baskerville/bspwm/issues/857#issuecomment-427670436
if [ "$instance" = lemonbar ]; then
    echo manage=off
    xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"
fi
