#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xdotool getwindowname "$wid")

case "$class" in
    Dragon|Dragon-drop)
        echo 'sticky=on' ;;
    Emacs)
        echo 'state=tiled' ;;
    Empty)
        echo 'state=tiled' ;;
    dmenu|\
        zoom|\
        Xfce4-panel|\
        Wrapper-2.0|\
        Blueman-manager|\
        Nm-connection-editor|\
        Wihotspot-gui|\
        pavucontrol|\
        Arandr|\
        Onboard|\
        Panther_launcher|\
        gnome-calculator|\
        org.gnome.clocks)
        echo 'state=floating' ;;
esac

case "$instance" in
    *__floatme__*)
        echo 'state=floating' ;;
esac

case "$title" in
    *__floatme__* | \
        'Python Turtle Graphics' | \
        'Picture in picture' | \
        'MetaMask Notification')
        echo 'state=floating' ;;
esac

case "$title" in
    *__stickme__*)
        echo 'sticky=on' ;;
esac

case "$class" in
    *__floatme__*)
        echo 'state=floating' ;;
esac

case "$class" in
    *__stickme__*)
        echo 'sticky=on' ;;
esac

case "$class" in
    XEyes)
        # xeyes -geometry 50x25+1
        echo 'manage=off'
        #echo 'rectangle=50x25+1+0'
        echo 'locked=on'
        echo 'sticky=on'
        echo 'state=floating' ;;
esac

case "$class" in
    Matplotlib)
        # move plot to the monitor on the right
        if [ "$(bspc query -M | wc -l)" -gt 1 ]; then # if we have such monitor
            d=$(bspc query -D --names | tail -n1)
            if [ -z "$(bspc query -N -d "$d")" ]; then # and is empty
                echo "desktop=$d"
            fi
        fi ;;
esac

# https://github.com/baskerville/bspwm/issues/857#issuecomment-427670436
if [ "$instance" = lemonbar ]; then
    echo manage=off
    xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"
fi
