#!/bin/sh

## This file is used to generate i3blocks.conf

OUTFILE="$HOME/.config/i3blocks/config"
rm -f "$OUTFILE"

out() { echo "$@" >> "$OUTFILE"; }

BINPATH=$(realpath "$0")
out "# DO NOT EDIT!
# Generated by $BINPATH
"

out command=/usr/lib/i3blocks/\$BLOCK_NAME
#out separator_block_width=20
out markup=pango

#out [close]
#out command=bar close
#out interval=once

out [donno]
out command=bar donno
out interval=once

out [language]
out command=bar lang
out interval=$I3BLOCKS_DUR_LANG
out signal=$I3BLOCKS_SIG_LANG

out [prayer]
out command=bar pray
out interval=$I3BLOCKS_DUR_PRAY
out signal=$I3BLOCKS_SIG_PRAY

out [weather]
out command=weather-update\; bar weat
out interval=$I3BLOCKS_DUR_WEAT
out signal=$I3BLOCKS_SIG_WEAT

out [sensors]
out command=bar sens
out interval=$I3BLOCKS_DUR_SENS
out signal=$I3BLOCKS_SIG_SENS

out [volume]
out command=bar volu
out interval=$I3BLOCKS_DUR_VOLU
out signal=$I3BLOCKS_SIG_VOLU

# out [brightness]
# out command=bar brig
# out interval=$I3BLOCKS_DUR_BRIG
# out signal=$I3BLOCKS_SIG_BRIG

out [wifi]
out command=bar wifi
out interval=$I3BLOCKS_DUR_WIFI
out signal=$I3BLOCKS_SIG_WIFI

out [battery]
out command=bar batt
out interval=$I3BLOCKS_DUR_BATT
out signal=$I3BLOCKS_SIG_BATT

out [time]
out command=bar clock
out interval=$I3BLOCKS_DUR_TIME
out signal=$I3BLOCKS_SIG_TIME
