#!/bin/sh

# Profile file. Runs on login.

export WINDOW_MANAGER='i3'
#export WINDOW_MANAGER='sway'
#export WINDOW_MANAGER='bspwm'
#export WINDOW_MANAGER='gnome-session'
export TERM="screen-256color"
export EDITOR="edit"
export VISUAL="$EDITOR"
export TERMINAL="st"
export BROWSER="browser"
export READER="evince" # TODO: mk a script, add foliate
export BIB="$HOME/Documents/LaTeX/refs.bib" # TODO: move to personal
export ORG_TODO="$HOME/Dropbox/orgmode/TODO.org" # TODO: move to personal

export FONT_MONO='Iosevka Fixed'
export FONT_SANS='Liberation Sans'
export FONT="$FONT_MONO"
export GTK_THEME="Adwaita:dark"
export DESKTOP_SESSION=gnome
export QT_QPA_PLATFORMTHEME="qt5ct"
#export QT_DEVICE_PIXEL_RATIO=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
#export QT_STYLE_OVERRIDE=adwaita-dark
export SHHH_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on' # check bashrc
export CLOUDCONVERT_API_KEY='bUGujVfvGQ6nkPZo5MvFoIz65C3spOZMtiD4Bz613XxnXsUIVDDwZILqOJZghP3D' # TODO: move to personal
export NEWT_COLORS='root=,black'

export PI=3.14159265358979323844
export EU=2.71828182845904523537

[ -f ~/.dotfiles-exports ] &&
    . ~/.dotfiles-exports
[ -f "$DOTFILES_DIR/configs/lficons.sh" ] &&
    . "$DOTFILES_DIR/configs/lficons.sh"
export TINY=$(ndots istiny && echo t)

# Workaround to not run those in Ubuntu
if ! command -v apt >/dev/null; then

    # To be able to change the brightness. Password is not required as edited in the sudoers
    sudo chmod a+rw /sys/class/backlight/intel_backlight/brightness \
         2>/dev/null ||:

    # Start graphical server if i3 not already running.
    if [ "$(tty)" = "/dev/tty1" ]; then
        pgrep -x "$WINDOW_MANAGER" || exec startx
    fi

fi
