#!/bin/sh

# Profile file. Runs on login.

export TERM='screen-256color'
export EDITOR='edit'
export VISUAL="$EDITOR"
export TERMINAL='theterm'
export FILE_MANAGER='fmz'
export BROWSER='ndots-gui browser'
export READER='ndots-gui reader'
export TUI_APPS='music-player:lf:vis:corona:alsamixer:lyrics:nano:dice:fmz'

# TODO: move to personal
export ORG_TODO="$HOME/Dropbox/orgmode/TODO.org"
export CLOUDCONVERT_API_KEY='bUGujVfvGQ6nkPZo5MvFoIz65C3spOZMtiD4Bz613XxnXsUIVDDwZILqOJZghP3D'

export SHHH_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on' # check bashrc
export NEWT_COLORS='root=,black'
#export LESS="$LESS --mouse -K"

export PI=3.14159265358979323844
export EU=2.71828182845904523537

[ -f ~/.dotfiles-exports ] && {
    . ~/.dotfiles-exports
    PATH="$PATH:$DOTFILES_SCRIPTS/gui"
    PATH="$PATH:$DOTFILES_SCRIPTS/tui"
    PATH="$PATH:$DOTFILES_SCRIPTS/tools"
    PATH="$PATH:$DOTFILES_SCRIPTS/personal"
    export PATH
}
export TINY=$(ndots istiny && echo t)

try_export() {   [ -d "$2" ] && export "$1=$2";:;       }
try_add_path() { [ -d "$1" ] && export PATH="$PATH:$1";:; }
test -f "$DOTFILES_DIR/configs/more-paths.sh" &&
    . "$DOTFILES_DIR/configs/more-paths.sh"

# Workaround to not run those in Ubuntu
if ! command -v apt >/dev/null; then

    # To be able to change the brightness. Password is not required as edited in the sudoers
    sudo chmod a+rw /sys/class/backlight/intel_backlight/brightness \
         2>/dev/null ||:

    # Start graphical server if i3 not already running.
    if [ "$(tty)" = "/dev/tty1" ]; then
        pgrep -x "$WINDOW_MANAGER" || exec startx
    fi

fi
