#!/bin/sh

[ $# = 1 ] || exit 1

wmf() {
    case "$1" in
        left)  o=right;;
        down)  o=up;;
        up)    o=down;;
        right) o=left;;
    esac
    #i3-msg focus "$o";
}

if ; then
    emacsclient --no-wait --eval "(windmove-$1)" && wmf "$1"
else
    wmf "$1"
fi
