#!/bin/sh

LANGS=us,ar
LANGS_E=us,ar,ru,fr,de,ir

# grep "grp:.*toggle" /usr/share/X11/xkb/rules/base.lst
KEYS=rctrl_rshift_toggle

langget() {
    setxkbmap -query | sed -En 's/layout:\s*(.+)/\1/p' 2>/dev/null
}

langinit() {
    langs=$LANGS
    [ "$1" = '-e' ] && langs=$LANGS_E
    setxkbmap -layout $langs -option grp:$KEYS
    [ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
}

langtog() {
    
}

main() {
    case "$1" in
        init)  shift; langinit "$@" ;;
        'tog') shift; langtog       ;;
        '')           langget       ;;
    esac
}

main "$@"
