#!/bin/sh
APK="$1"
shift
KEY=~/.android/debug.keystore
[ -f "$1" ] && KEY="$1" && shift
/usr/lib/jvm/java-16-openjdk/bin/jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore "$KEY" "$APK" androiddebugkey -storepass android "$@"
