#!/bin/sh

MAX_VOL=500

notif() {
    V=$(pamixer --get-volume)
	if [ "$(pamixer --get-mute)" = "true" ] || [ "$V" = 0 ]; then
        V="Muted"
	else
		V="$V%"
    fi
	dunstify -i none -r 123 "Volume: $V"
}

vol() {
    LOCK='/tmp/__audioctl_vol_lock'
    [ -f "$LOCK" ] && return
    touch "$LOCK"
    C="$1"
    if [ "$C" = m ]; then
        pamixer -m
    elif [ "$C" = t ]; then
        pamixer -t
    else
        V=$(pamixer --get-volume)
        V=$((V+C))
        if [ $V -le $MAX_VOL ]; then
            V=$((V/5*5))
            pamixer --allow-boost --set-volume $V
        fi
    fi
    rm -f "$LOCK"
	notif
}

vol() {
    case "$1" in
        t) amixer -q set Master toggle;;
        m) amixer -q set Master mute;;
        *)
            V="$1"
            if [ "$V" -ge 0 ]; then
                amixer -q set Master "$V%+"
            else
                V=$((-V))
                amixer -q set Master "$V%-"
            fi;;
    esac
	notif
}

V="$2"
case "$1" in
	"up")       vol "$V"  ;;
	"down")     vol "-$V" ;;
	"mute")     vol t     ;;
	"truemute") vol m     ;;
	"stop")     mpc -q stop       || cmus-remote --stop       ;;
	"pause")    mpc -q toggle     || cmus-remote --pause      ;;
	"forward")  mpc -q seek +"$V" || cmus-remote --seek +"$V" ;;
	"back")     mpc -q seek -"$V" || cmus-remote --seek -"$V" ;;
	"next")     mpc -q next       || cmus-remote --next       ;;
	"prev")     mpc -q prev       || cmus-remote --prev       ;;
	"replay")   mpc seek 0%       || cmus-remote --seek 0     ;;
esac 2>/dev/null
