#!/bin/sh

awesomefontecho() {
    printf '<span font="Font Awesome 5 Free" rise="-1024"'
    [ "$2" ] && printf ' color="%s"' "$2"
    printf '>'
    printf "$1" # FIXME for POSIX
    printf '</span>'
}

clock() {
    [ "$BLOCK_BUTTON" = "1" ] && theterm "cal -y && read" &
    D=$(date '+%a %Y-%m-%d %I:%M:%S %p')
    printf '%s' "$D"
}

batt() {
    V=$(cat /sys/class/power_supply/BAT1/capacity 2>/dev/null)
    C=$(cat /sys/class/power_supply/BAT1/status   2>/dev/null)

    if [ ! "$V" ] || [ ! "$C" ]; then
        B=$(acpi -b)
        V=$(echo "$B" | awk -F'[,:%]' '{print $3}')
        C=$(echo "$B" | awk -F'[, ]'  '{print $3}')
    fi

    R=''

    if [ "$1" = "-a" ]; then
        if [ "$C" != 'Discharging' ]; then
            printf '~'
        fi
        printf "%d%%" "$V"
        return
    fi

    if [ "$C" != 'Discharging' ]; then
        R='#FFD700'
        awesomefontecho '\uf1e6' $R
        printf ' '
    elif [ "$V" -le "5" ]; then
        R='#FF0000'
        awesomefontecho '\uf12a' $R
        printf ' '
    elif [ "$V" -le "20" ]; then
        R='#FF0000'
    fi

    if [ "$V" -lt "50" ]; then
        awesomefontecho '\uf243' $R
    elif [ "$V" -lt "60" ]; then
        awesomefontecho '\uf242' $R
    elif [ "$V" -lt "90" ]; then
        awesomefontecho '\uf241' $R
    else
        awesomefontecho '\uf240' $R
    fi

    printf " %d%%" "$V"

    battery-check "$V" "$C" &
}

wifi() {
    [ "$BLOCK_BUTTON" = "1" ] && networkmanager_dmenu
    V=$(awk 'NR==3 {print $3}' /proc/net/wireless)
    [ "$V" != '' ] && {
        [ "$1" != "-a" ] && \
            awesomefontecho '\uf1eb' && printf ' '
        printf '%.0f%%' "$V"
    }
}

brig() {
    [ "$BLOCK_BUTTON" = "1" ] && dmenudisplay
    [ "$1" != "-a" ] && awesomefontecho '\uf108' && echo -n ' '
    printf '%s%%' "$(brightness -print)"
}

volu() {
    case "$BLOCK_BUTTON" in
	      1) theterm pulsemixer & ;;
	      3) pamixer -t ;;
	      4) pamixer -i 5 ;;
	      5) pamixer -d 5 ;;
    esac
    V=$(pamixer --get-volume)
    if [ "$1" != "-a" ]; then
        if [ "$(pamixer --get-mute)" = "true" ] || [ "$V" = 0 ]; then
            awesomefontecho '\uf026'
            awesomefontecho '\uf00d'
        else
            awesomefontecho '\uf028'
        fi
        printf ' '
    fi
    printf "%d%%" "$V"
}

sens() {
    [ "$BLOCK_BUTTON" = "1" ] && theterm popsensors &
    O=$(sensors coretemp-isa-0000 -j | jq '.["coretemp-isa-0000"]["Package id 0"]')
    T=$(echo "$O" | jq '.["temp1_input"]')
    M=$(echo "$O" | jq '.["temp1_max"]')
    if [ "$1" != "-a" ]; then
        P=$(echo "$T/$M*100" | bc -l)
        P=$(printf '%.0f' "$P")
        if [ "$P" -ge "90" ]; then
            awesomefontecho '\uf12a' '#FF0000'
            printf ' '
            awesomefontecho '\uf2c7' '#FF0000'
        elif [ "$P" -gt "50" ]; then
            awesomefontecho '\uf2c8'
        elif [ "$P" -gt "40" ]; then
            awesomefontecho '\uf2c9'
        else
            awesomefontecho '\uf2ca'
        fi
        printf ' '
    fi
    printf '%s°C' "$T"
}

weat() {
    [ "$BLOCK_BUTTON" = "1" ] && theterm popweather &
    #                          Lines from 3rd to 4th        Remove color codes                Cut
    V=$(sed -n -e "3,4 p" -e "4 q" ~/.weatherreport | sed "s/\x1B\[[0-9;]*[JKmsu]//g" | cut -c 16-)
    #S=$(echo "$V" | head -1 | awk '{print tolower($0)}')
    W=$(echo "$V" | tail -1 | awk -F'[- ]' '{print $1}')
    [ "$1" != "-a" ] && awesomefontecho '\uf0c2' && printf ' '
    printf '%s°C' "$W"
}

pray() {
    [ "$BLOCK_BUTTON" = "1" ] && theterm popprayer &
    [ "$1" != "-a" ] && awesomefontecho '\uf186' && printf ' '
    printf '%s' "$(p n)"
}

lang() {
    arg='-v'
    [ "$BLOCK_BUTTON" = "1" ] && arg=''
    printf '%s' "$(lang-toggle $arg)"
}

host() {
    printf '%s' "$(hostname)"
}

cmus() {
    Q=$(cmus-remote -Q 2>/dev/null)
    [ ! "$Q" ] && return
    T=$(echo "$Q" | sed -rn 's/tag title (.+)/\1/p')
    A=$(echo "$Q" | sed -rn 's/tag artist (.+)/\1/p')
    S=$(echo "$Q" | sed -rn 's/status (.+)/\1/p')
    [ "$1" != "-a" ] && {
        [ "$S" = 'playing' ] && awesomefontecho '\uf04b'
        [ "$S" = 'paused' ]  && awesomefontecho '\uf04c'
        printf ' '
    }
    printf '%s - %s' "$T" "$A"
}

donno() {
    [ "$BLOCK_BUTTON" = "1" ] && theterm 'lolcowforune -p' &
    echo '¯\_(ツ)_/¯'
}

if [ "$1" = '-a' ]; then
    a='-a'
    sep=" | "
    shift
else
    sep="  "
fi

count=0
end=$(($# - 1))
for arg in "$@"; do
    eval "$arg" $a
    [ $count -lt $end ] && printf '%s' "$sep"
    count=$((count+1))
done
echo
