#!/bin/sh

B="$1"
C="$2"
TF='/tmp/.battery-low'
[ "$C" != 'Discharging' ] && {
    rm -f "${TF}"*
    exit
}
if [ ! -e "$TF-$B" ]; then
    rm -f "${TF}"*
    touch "$TF-$B"
    if [ "$B" -le "5" ]; then
        echo LOW BATTERY SHUTTING DOWN
        lockscreen && systemctl hibernate
    elif [ "$B" -le "7" ]; then
        notify-send -u critical "VERY LOW BATTERY ${B}% WILL SHUTDOWN AT 5%!!!"
    elif [ "$B" -eq "10" ]; then
        notify-send -u critical "Low battery ${B}%"
    fi
fi
