#!/bin/bash
B="$1"
C="$2"
TF='/tmp/.battery-low'
[[ "$C" != 'Discharging' ]] && {
    rm -f "${TF}"*
    exit
}
if [[ ! -e "$TF-$B" ]]; then
    rm -f "${TF}"*
    touch "$TF-$B"
    if [[ "$B" -le "2" ]]; then
        echo LOW BATTERY SHUTTING DOWN
        systemctl poweroff
    elif [[ "$B" -le "3" ]]; then
        notify-send -u critical "VERY LOW BATTERY ${B}% WILL SHUTDOWN AT 2%!!!"
    elif [[ "$B" -eq "5" ]]; then
        notify-send -u critical "Low battery ${B}%"
    fi
fi
