#!/bin/bash
MAX=661
MIN=10
file="/sys/class/backlight/intel_backlight/brightness"
current=$(cat "$file")
C="$1"
V="$2"
if [[ "$C" = "-print" ]]; then
    P=$(echo "$current/$MAX*100" | bc -l)
    printf "%.0f\n" $P
    exit
fi
new="$current"
if [[ "$V" != "" ]]; then
    val=$(echo "$V*$MAX/100" | bc)
fi
if [[ "$C" = "-set" ]]; then
    new=$val
    if [[ "$new" -gt "$current" ]]; then
        C='-inc'
    else
        C='-dec'
    fi
elif [[ "$C" = "-inc" ]]; then
    new=$(( current + $val ))
elif [[ "$C" = "-dec" ]]; then
    new=$(( current - $val ))
fi
if [[ $new -gt $MAX ]]; then
    new=$MAX
elif [[ $new -lt $MIN ]]; then
    new=$MIN
fi

while [[ "$current" != "$new" ]]; do
    if [[ "$C" = "-inc" ]]; then
        current=$((current + 1))
    elif [[ "$C" = "-dec" ]]; then
        current=$((current - 1))
    fi
    echo $current > "$file"
    sleep 0.0001
done

pkill -RTMIN+3 i3blocks
