#!/bin/sh

e() { command -v "$1" >/dev/null; }

x=$(xdpyinfo | sed -rn 's/\s*dimensions:\s+([0-9]+)x([0-9]+) .+/\1/p')
if [ "$x" -ge 1920 ]; then
    scale=1.3
else
    scale=1
fi

if e brave; then
    exec brave --force-device-scale-factor="$scale" "$@"
elif e chromium; then
    exec chromium --force-device-scale-factor="$scale" "$@"
elif e firefox; then
    exec firefox "$@"
else
    notify-send -u critical 'No installed web browser was found'
fi
