#!/bin/sh

e() { command -v "$1" >/dev/null; }

if e brave; then
    exec brave --force-device-scale-factor=1.3 "$@"
elif e chromium; then
    exec chromium --force-device-scale-factor=1.3 "$@"
elif e firefox; then
    exec firefox "$@"
else
    notify-send -u critical 'No installed web browser was found'
fi
