#!/bin/sh

notify() {
    notify-send "$@" >/dev/null 2>/dev/null &
}

I="$HOME/.cache/copy-text-image.png"
maim --hidecursor -s "$I"
notify 'Reading screen...'
tesseract "$I" "$I"
notify 'Screen content copied'
sed 's/\x0c//g' "$I.txt" | clipboard
rm -f "$I" "$I.txt"
