#!/bin/bash
RES=$(echo -e "Suspend\nShutdown\nReboot\nLogout\nLock\nHibernate" | menu-interface -i -p 'Power options')
function confirm {
    R=$(echo -e "Yes\nNo" | menu-interface -p "$RES?" -i -sb red -nf red)
    [[ "$R" = "Yes" ]]
}
case "$RES" in
    Lock)
        lockscreen;;
    Logout)
        confirm && i3-msg exit;;
    Suspend)
        lockscreen && systemctl suspend;;
    Hibernate)
        confirm && lockscreen && systemctl hibernate;;
    Reboot)
        confirm && systemctl reboot;;
    Shutdown)
        confirm && systemctl poweroff;;
    *)
        exit 1
esac
