#!/bin/sh

# TODO: move to personal

D="$HOME/.dotfiles/display-layouts"

OPTS=\
'Invert colors
Temperature: 6500  Default
Temperature: 5000  Warm
Temperature: 9000  Cool
Temperature: 2000  Extra Warm
Temperature: 20000 Extra Cool
Temperature: Custom
Edit screen layout'

if [ "$1" = '-d' ]; then
    sel='Default'
else
    sel=$( (echo Default &&
                ls -1 "$D/" | grep -v default | awk -F'.' '{print $1}' &&
                echo "$OPTS") |
               menu-interface -i -l 30 -p 'Display options')
fi

case "$sel" in
    '');;
    Default)
        xsct 6500
        sh "$D/default.sh";;
    Edit*)
        arandr;;
    Invert*)
        xrandr-invert-colors;;
    Temperature*)
        sel=$(echo "$sel" | awk '{print $2}')
        if [ "$sel" = Custom ]; then
            sel=$(echo | menu-interface -i -l 20 -p 'Color temperature')
        fi
        [ "$sel" ] && xsct "$sel";;
    *)
        sh "$D/${sel}.sh";;
esac

setwallpaper
