#!/bin/bash
# Gives a dmenu prompt to mount unmounted drives.
# If they're in /etc/fstab, they'll be mounted automatically.
# Otherwise, you'll be prompted to give a mountpoint from already existsing directories.
# If you input a novel directory, it will prompt you to create that directory.
# https://github.com/Naheel-Azawy/naheel-dotfiles
# Based on https://github.com/LukeSmithxyz/voidrice

LEN=20

function getmount {
	  [ -z "$chosen" ] && exit 1
	  mp="$(find $1 | dmenu -l $LEN -i -p "Type in mount point.")"
	  [ "$mp" = "" ] && exit 1
	  if [ ! -d "$mp" ]; then
		    mkdiryn=$(printf "No\\nYes" | dmenu -i -p "$mp does not exist. Create it?")
		    [ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
	  fi
}

function mountusb {
	  chosen=$(echo "$1" | awk '{print $2}')
	  sudo -A mount "$chosen" && notify-send "$chosen mounted." && exit 0
	  getmount "/mnt -maxdepth 1 -type d"
	  sudo -A mount "$chosen" "$mp" && notify-send "$chosen mounted to $mp."
}

function mountmtp {
	  chosen=$(echo "$1" | awk -F':' '{print $2}' | xargs)
	  getmount "/mnt -maxdepth 1 -type d"
	  simple-mtpfs --device "$chosen" "$mp"
	  notify-send "MTP device mounted to $mp."
}

mtpdrives=$(simple-mtpfs -l 2>/dev/null | awk '{print "MTP:   "$0}')
usbdrives=$(test ! -z "$mtpdrives" && echo "$mtpdrives"; \
            lsblk -rpo "name,type,size,mountpoint" | awk '($2=="part"||$2=="lvm")&&$4==""{printf "DRIVE: %s (%s)\n",$1,$3}')

chosen=$(echo "$usbdrives" | dmenu -l $LEN -i -p "Mount which drive?")
echo "$chosen" | grep -q "MTP:" && mountmtp "$chosen" || mountusb "$chosen" && {
            open=$(echo -e "No\nRanger\nLF\nTerminal" | dmenu -i -p "Open $mp?")
            cd "$mp"
            case "$open" in
                Ranger)   exec $TERMINAL -e tmux-quick ranger;;
                LF)       exec $TERMINAL -e tmux-quick lf;;
                Terminal) exec $TERMINAL -e tmux-quick;;
            esac
        }
