#!/bin/bash
D="$1"
#open=$(echo -e "Terminal\nLF\nRanger\nNNN\nNautilus" | menu-interface -i -p "Open $(basename $D)?")
open='Terminal'
cd "$D"
case "$open" in
    Ranger)   exec theterm ranger;;
    LF)       exec theterm lf;;
    NNN)      exec nnn;;
    Nautilus) exec nautilus .;;
    Terminal) exec theterm;;
esac
