#!/bin/sh

VIDEO_DIR="$HOME/Videos/YouTube"
AUDIO_DIR="$HOME/Music/YouTube"
PROG_FILE="/tmp/__ytdl_prog"

DMENU="menu-interface -sb '#E00000' -sf white -nf white"

search() {
    Q=$(echo | eval "$DMENU -p 'Search YouTube'" | url-encode) &&
        [ "$Q" ] &&
        browser "https://www.youtube.com/results?search_query=$Q"
}

[ "$1" = '-p' ] && {
    tail -f "$PROG_FILE"
    exit
}
mkdir -p "$VIDEO_DIR"
mkdir -p "$AUDIO_DIR"
CLIP=$(clipboard)
CURRENT=$(xdotool getactivewindow)
BROWSER=$(xdotool search --onlyvisible --class "chromium") ||
    BROWSER=$(xdotool search --onlyvisible --class "brave") ||{
    search
    exit
}
sleep 0.5 # To give the user a chance to release the keyboard
BROWSER=$(echo "$BROWSER" | awk '{print $1}')
xdotool windowfocus "$BROWSER"
xdotool key ctrl+l
xdotool key ctrl+c
xdotool key Tab
xdotool windowfocus "$CURRENT"
URL=$(clipboard)
echo "$CLIP" | clipboard
echo "$URL" | grep -q youtube || {
    search
    exit
}
TITLE=$(xprop -id "$BROWSER" | \
            sed -rn 's/_NET_WM_NAME\(UTF8_STRING\) = "(.*)"/\1/p' | \
            sed 's/ - YouTube.*//g' | \
            cut -c -50 | \
            fribidi --nopad)
echo "$URL" | grep -q 'playlist' || MENU='Download\nDownload audio\n'
echo "$URL" | grep -q 'list=' && MENU="${MENU}Download playlist\nDownload audio playlist\n"
MENU="${MENU}Copy URL\nWatch in YouTube viewer"
D=0
RES=$(echo -e "$MENU" | eval "$DMENU -l 20 -p \"$TITLE\"") || exit
echo "$RES" | grep -q Download && D=1
[[ $D == 1 ]] && notify-send "Downloading $TITLE..."
case "$RES" in
    'Download')
        cd "$VIDEO_DIR"
        youtube-dl --add-metadata -ic --no-playlist "$URL" &>"$PROG_FILE";;
    'Download playlist')
        cd "$VIDEO_DIR"
        youtube-dl --add-metadata -ic "$URL" &>"$PROG_FILE";;
    'Download audio')
        cd "$AUDIO_DIR"
        youtube-dl --add-metadata -xic --audio-format mp3 --no-playlist "$URL" &>"$PROG_FILE";;
    'Download audio playlist')
        cd "$AUDIO_DIR"
        youtube-dl --add-metadata -xic --audio-format mp3 "$URL" &>"$PROG_FILE";;
    Copy*)
        echo -n "$URL" | clipboard
        exit 0;;
    Watch*)
        youtube-viewer "$URL";;
esac
[ $D = 1 ] && notify-send "YouTube download for $TITLE completed"

