#!/bin/bash
# A dmenu prompt to unmount drives.
# Provides you with mounted partitions, select one to unmount.
# Drives mounted at /, /boot and /home will not be options to unmount.
# https://github.com/Naheel-Azawy/naheel-dotfiles
# Based on https://github.com/LukeSmithxyz/voidrice

LEN=20

mtpdrives=$(awk '/simple-mtpfs/ {print $2 ": (MTP)"}' /etc/mtab)
drives=$(test ! -z "$mtpdrives" && echo "$mtpdrives"; lsblk -nrpo "name,type,size,mountpoint" | awk '($2=="part"||$2=="lvm")&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s: %s (%s)\n",$4,$1,$3}' | sort)
[ -z "$drives" ] && exit
chosen=$(echo "$drives" | dmenu -l $LEN -i -p "Unmount which drive?")
MTP=$(echo "$chosen" | grep -q "(MTP)" && echo 1 || echo 0)
chosen=$(echo "$chosen" | awk -F':' '{print $1}')
[ -z "$chosen" ] && exit
notify-send "unmouning $chosen..."
sync && [[ "$MTP" == 0 ]] && sudo -A umount "$chosen" || fusermount -u "$chosen" && notify-send "$chosen unmounted." || notify-send "Error unmounting $chosen"
