#!/bin/bash
WORDS="¯\\_(ツ)_/¯
السلام عليكم
السلام عليكم و رحمة الله و بركاته
و عليكم السلام و رحمة الله و بركاته
Alsalamu alykum
naheelazawy@gmail.com
nk1508530@qu.edu.qa
(☞ﾟヮﾟ)☞ ☜(ﾟヮﾟ☜)
(☞ﾟ∀ﾟ)☞
◔ ⌣ ◔
( ͡° ͜ʖ ͡°)
( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)"
R=$(echo "$WORDS" | menu-interface -l 15 -p 'Words')
[[ "$R" != '' ]] && echo -n "$R" | clipboard
