#!/bin/sh

if [ ! "$1" ]; then
    RES=$(printf "Suspend\nShutdown\nReboot\nLogout\nLock\nHibernate" | menu-interface -i -p 'Power options')
else
    RES="$1"
fi

confirm() {
    R=$(printf "Yes\nNo" | menu-interface -p "$RES?" -i -sb red -nf red)
    [ "$R" = "Yes" ]
}

case "$RES" in
    Lock)
        lockscreen;;
    Logout)
        confirm && i3-msg exit;;
    Suspend)
        lockscreen && systemctl suspend;;
    Hibernate)
        confirm && lockscreen && systemctl hibernate;;
    Reboot)
        confirm && systemctl reboot;;
    Shutdown)
        confirm && systemctl poweroff;;
    *)
        exit 1
esac
