#!/bin/sh

DMENU='menus-face -i'

is_url() {
    [ "$(echo "$1" | sed -rn 's@.*(https?://.+\..+).*@\1@p')" != '' ]
}

how_can_I_help_you_sir() {
    C=$( (is_url "$Q" &&
              echo "View page";
          echo "Wikipedia"      &&
              echo "Dictionary" &&
              echo "Duck it!"   &&
              echo "Manual"     &&
              echo "ArchWiki"   &&
              echo "Wait... What? I'm looking for something else...") |
             $DMENU -l 20 -p "What is $Q?")

    case "$C" in
        View*)
            theterm "bash -c 'lynx -dump \"$Q\" | more && echo -e \"\nOpen in browser? (y/n)\" && read ans && test \"\$ans\" == y && browser \"$Q\" &>/dev/null'"
            ;;
        Wiki*)
            theterm "wikit-quick \"$Q\""
            ;;
        Dict*)
            L=$(printf 'en\nar' | $DMENU -p 'To?')
            theterm "trans :$L \"$Q\" | less -R"
            ;;
        Duck*)
            Q=$(echo "$Q" | url-encode)
            $BROWSER "https://duckduckgo.com/?q=$Q&t=ffab&atb=v1-1"
            ;;
        Man*)
            theterm "man \"$Q\""
            ;;
        Arch*)
            Q=$(echo "$Q" | url-encode)
            $BROWSER "https://wiki.archlinux.org/index.php?search=$Q"
            ;;
        Wait*)
            Q=$(echo | $DMENU -p "Which is?")
            how_can_I_help_you_sir
            ;;
    esac
}

get_selected() {
    clipboard
    #BAK=$(clipboard)
    #sleep .1
    #xdotool key ctrl+c
    #sleep 5
    #clipboard
    #printf "%s" "$BAK" | clipboard
}

Q=$(get_selected | tr '\n' ' ' | head -c 50 | xargs)
[ ! "$Q" ] && exit 1
how_can_I_help_you_sir
