#!/bin/bash
WORDS="¯\\_(ツ)_/¯
السلام عليكم
السلام عليكم و رحمة الله و بركاته
و عليكم السلام و رحمة الله و بركاته
Alsalamu alykum
naheelazawy@gmail.com
nk1508530@qu.edu.qa"
R=$(echo "$WORDS" | dmenu -l 15)
[[ "$R" != '' ]] && echo -n "$R" | clipboard
