#!/bin/bash
# Quick search on DuckDuckGo
# https://github.com/Naheel-Azawy/naheel-dotfiles
# Based on https://github.com/LukeSmithxyz/voidrice

choice=$(echo "🦆" | dmenu -sb '#D94824' -nf '#D94824' -i -p "Search DuckDuckGo:") || exit 1

if [ "$choice" = "🦆"  ]; then
	  $BROWSER "https://duckduckgo.com"
else
	  $BROWSER "https://duckduckgo.com/?q=$choice&t=ffab&atb=v1-1"
fi
