#!/bin/bash

DMENU='menu-interface -i'

function is-url {
    [[ $(echo "$1" | sed -rn 's@.*(https?://.+\..+).*@\1@p') != '' ]]
}

function how-can-I-help-you-sir {
    C=$((is-url "$Q" && \
             echo "View page";   \
             echo "Wikipedia" && \
             echo "Translate" && \
             echo "Duck it!"  && \
             echo "Manual"    && \
             echo "ArchWiki"  && \
             echo "Wait... What? I'm looking for something else...") \
            | $DMENU -l 20 -p "What is ${Q:0:30}?")

    case "$C" in
        View*)
            theterm "bash -c 'lynx -dump \"$Q\" | more && echo -e \"\nOpen in browser? (y/n)\" && read ans && test \"\$ans\" == y && browser \"$Q\" &>/dev/null'"
            ;;
        Wiki*)
            theterm "wikit-quick \"$Q\""
            ;;
        Trans*)
            L=$(echo -e 'en\nar' | $DMENU -p 'To?')
            theterm "trans :$L \"$Q\" | less -R"
            ;;
        Duck*)
            Q=$(echo "$Q" | url-encode)
            $BROWSER "https://duckduckgo.com/?q=$Q&t=ffab&atb=v1-1"
            ;;
        Man*)
            theterm "man \"$Q\""
            ;;
        Arch*)
            Q=$(echo "$Q" | url-encode)
            $BROWSER "https://wiki.archlinux.org/index.php?search=$Q"
            ;;
        Wait*)
            Q=$(echo | $DMENU -p "Which is?")
            how-can-I-help-you-sir
            ;;
    esac
}

Q=$(clipboard | tr '\n' ' ' | xargs)
how-can-I-help-you-sir
