#!/bin/sh
# Little hack... No idea why but dmenu messes the foucs

doit() {
    xdotool getactivewindow windowfocus
}

main() {
    doit
    if [ "$1" = '-l' ]; then
        for s in .2 .3 .5; do
            sleep $s
            doit
        done
    fi
}

main "$@" >/dev/null 2>/dev/null
exit 0
