#!/bin/bash
# Gives a dmenu prompt to mount unmounted drives.
# If they're in /etc/fstab, they'll be mounted automatically.
# Otherwise, you'll be prompted to give a mountpoint from already existsing directories.
# If you input a novel directory, it will prompt you to create that directory.
# https://github.com/Naheel-Azawy/naheel-dotfiles
# Based on https://github.com/LukeSmithxyz/voidrice

LEN=15

function getmount {
	  [ -z "$chosen" ] && exit 1
    mps=$(diff --changed-group-format='%>' --unchanged-group-format='' \
               <(lsblk -rpo "mountpoint" | grep . | sort) \
               <(find /mnt -maxdepth 1 -type d | sort) | \
              tail -n +2)
	  #mp=$(echo "$mps" | menu-interface -l $LEN -i -p "Type in mount point.")
    mp=$(echo "$mps" | head -n 1)
	  [ "$mp" = "" ] && exit 1
	  if [ ! -d "$mp" ]; then
		    mkdiryn=$(printf "No\\nYes" | menu-interface -i -p "$mp does not exist. Create it?")
		    [ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
	  fi
}

function mountusb {
	  chosen=$(echo "$1" | awk '{print $2}')
	  sudo -A mount "$chosen" && notify-send "$chosen mounted." && exit 0
	  getmount
	  sudo -A mount "$chosen" "$mp" && notify-send "$chosen mounted to $mp."
}

function mountmtp {
	  chosen=$(echo "$1" | awk -F':' '{print $2}' | xargs)
	  getmount
	  simple-mtpfs --device "$chosen" "$mp"
	  notify-send "MTP device mounted to $mp."
}

mtpdrives=$(simple-mtpfs -l 2>/dev/null | awk '{print "MTP:   "$0}')
usbdrives=$(test ! -z "$mtpdrives" && echo "$mtpdrives"; \
            lsblk -rpo "name,type,size,mountpoint" | awk '($2=="part"||$2=="lvm")&&$4==""{printf "DRIVE: %s (%s)\n",$1,$3}')

chosen=$(echo "$usbdrives" | menu-interface -l $LEN -i -p "Mount which drive?")
echo "$chosen" | grep -q "MTP:" && mountmtp "$chosen" || mountusb "$chosen" && dmenuopendir "$mp"
