#!/bin/sh

DMENU="menu-interface -i -l 20"
DMENUL="$DMENU"

RUN=$(launcherhelper | $DMENU)
[ ! "$RUN" ] && exit 1

clean() {
    RUN=$(echo "$RUN" | sed -e 's/^!.\s*//')
}

term() {
    exec theterm "$RUN; fish"
}

calculate() {
    exec theterm "calc \"$RUN\"; calc"
}

duck() {
    RUN=$(echo "$RUN" | url-encode)
    exec "$BROWSER" "https://duckduckgo.com/?q=$RUN&t=ffab&atb=v1-1"
}

findfile() {
    L=$(locate "$RUN")
    [ ! "$L" ] && {
        notify-send "'$RUN' not found!"
        return
    }
    F=$(echo "$L" | eval "$DMENUL")
    N=$(basename "$F")
    case $(printf 'Open\nOpen directory' |
               eval "$DMENU -p 'Open $N?'") in
        'Open')
            exec open "$F"
            ;;
        'Open directory')
            D=$(dirname "$F")
            exec dmenuopendir "$D"
            ;;
    esac
}

# needed to update the database of locate
sudo updatedb &

dmenufixfocus -l 2>/dev/null &

case $RUN in
    \!t*) clean; term;;
    \!c*) clean; calculate;;
    \!d*) clean; duck;;
    \!f*) clean; findfile;;
    \!s*) clean; exec theterm "sudo $RUN";;
    *)    launcherhelper run "$RUN";;
esac
