#!/bin/sh

# https://gist.github.com/evanscottgray/8571828#gistcomment-1830482

# Stop all containers:
docker kill "$(docker ps -q)"

# Remove all containers
docker rm "$(docker ps -a -q)"

# Remove all docker images
docker rmi "$(docker images -q)"
