#!/bin/sh

# Tiny interface to emacs

#BIDI=1

BINPATH=$(realpath "$0")

LD_LIBRARY_PATH= # to fix miniconda issues
export TERM='screen-256color'

daemon() { emacsclient -e 0 >/dev/null || emacs --daemon "$@"; }
die()    { exec emacsclient -e '(kill-emacs)'; }
client() { daemon; emacsclient "$@"; }

gui() { client -c "$@"; }
existing() { client -n "$@"; }
tnw() { exec theterm "$BINPATH" nw "$@"; }
nw()  {
    tmux set automatic-rename off 2>/dev/null
    client -nw "$@"
    tmux set automatic-rename on 2>/dev/null
}

swallowable() {
    [ -n "$DISPLAY" ]                 &&
        [ -t 0 ]                      &&
        [ "$THETERM_TERM" = xterm ]   &&
        [ "$WINDOW_MANAGER" = bspwm ] &&
        command -v emacs >/dev/null   &&
        command -v xdotool >/dev/null &&
        command -v xdo >/dev/null
}
swallow() {
    (gui "$@") > /dev/null 2>&1 &
    cls=
    count=0
    while [ "$cls" != Emacs ]; do
        [ "$count" -ge 50 ] && {
            echo 'Timeout!!!' >&2
            return
        }
        cls=$(xdotool getactivewindow getwindowclassname)
        count=$((count + 1))
        sleep .1
    done
    bspc node -s last.local
    bspc node -f last.local
    id=$(xdo id)
    bspc node "$id" --flag hidden=on
    wait
    bspc node "$id" --flag hidden=off
    bspc node -f "$id"
}

[ "$BIDI" ] &&
    nw() { exec bicon.bin --reshape-only "$BINPATH" c -nw "$@" 2>/dev/null; }

mem() {
    kb=$(sed -rn 's/MemTotal: +([0-9]+) kB/\1/p' /proc/meminfo)
    echo $((kb / 1000000))
}

if ! command -v emacs >/dev/null || [ "$(mem)" -le 2 ]; then
    # emacs is not installed, assume nano is
    daemon() { :; }
    die()    { :; }
    client() { exec nano "$@"; }

    tnw() { exec theterm "$BINPATH" nw "$@"; }
    gui() { tnw "$@"; }
    existing() { gui "$@"; }
    nw()  { client "$@"; }
fi

mk_desktop() {
    [ -f ~/.local/share/applications/editor.desktop ] && return
    mkdir -p ~/.local/share/applications/
    {
        echo '[Desktop Entry]'
        echo 'Name=Editor'
        echo 'Comment=Edit text'
        echo 'MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;'
        echo 'Exec=edit g %F'
        echo 'Icon=emacs'
        echo 'Categories=Development;TextEditor;'
    } > ~/.local/share/applications/editor.desktop
}

main() {
    mk_desktop
    CMD="$1"
    case "$CMD" in
        d|daemon)   shift && daemon   "$@";;
        k|kill|die)          die          ;;
        c|client)   shift && client   "$@";;
        e|existing) shift && existing "$@";;
        g|gui)      shift && gui      "$@";;
        n|nw)       shift && nw       "$@";;
        t|tnw)      shift && tnw      "$@";;
        *)
            if [ "$EMACS_VTERM_PATH" ]; then
                existing "$@"
            elif swallowable; then
                swallow "$@"
            elif [ -t 0 ]; then
                nw "$@"
            else
                gui "$@"
            fi;;
    esac
}

main "$@"
