#!/bin/bash
V=$(cat /sys/class/power_supply/BAT1/capacity 2>/dev/null)
C=$(cat /sys/class/power_supply/BAT1/status 2>/dev/null)

if [ "$V" = "" ] || [ "$C" = "" ]; then
     B=$(acpi -b)
     V=$(echo $B | awk -F'[,:%]' '{print $3}')
     C=$(echo $B | awk -F'[, ]' '{print $3}')
fi

R=''

if [ "$1" = "-a" ]; then
    if [ "$C" != 'Discharging' ]; then
        echo -n "~"
    fi
    printf "%d%%\n" $V
    exit
fi

if [ "$C" != 'Discharging' ]; then
    R='gold'
    awesome-font-echo '\uf1e6' $R
    echo -n ' '
elif [ "$V" -le "5" ]; then
    R='red'
    awesome-font-echo '\uf12a' $R
    echo -n ' '
elif [ "$V" -le "20" ]; then
    R='red'
fi

if [ "$V" -lt "50" ]; then
    awesome-font-echo '\uf243' $R
elif [ "$V" -lt "60" ]; then
    awesome-font-echo '\uf242' $R
elif [ "$V" -lt "90" ]; then
    awesome-font-echo '\uf241' $R
else
    awesome-font-echo '\uf240' $R
fi

printf " %d%%\n" $V
