#!/bin/bash

case $BLOCK_BUTTON in
	  1) $TERMINAL -e pulsemixer & disown ;;
	  3) pamixer -t ;;
	  4) pamixer -i 5 ;;
	  5) pamixer -d 5 ;;
esac

V=$(pamixer --get-volume)

if [ $(pamixer --get-mute) = "true" ] || [ $V = 0 ]; then
    awesome-font-echo '\uf026\uf00d'
elif [ "$V" -le "20" ]; then
    awesome-font-echo '\uf027'
else
    awesome-font-echo '\uf028'
fi
printf " %d%%" $V
