#!/bin/bash
[[ $BLOCK_BUTTON = "1" ]] && st -e popweather
weather-update
#                          Lines from 3rd to 4th        Remove color codes                Cut
V=$(cat ~/.weatherreport | sed -n -e "3,4 p" -e "4 q" | sed "s/\x1B\[[0-9;]*[JKmsu]//g" | cut -c 16-)
S=$(echo "$V" | head -1 | awk '{print tolower($0)}')
W=$(echo "$V" | tail -1 | awk -F'[- ]' '{print $1 $3}')
[ "$1" != "-a" ] && awesome-font-echo '\uf0c2' && echo -n ' '
echo "$W"
