#!/bin/bash
# if this doesn't work, run this
# sudo chmod a+rw /sys/class/backlight/intel_backlight/brightness
[[ $BLOCK_BUTTON = "1" ]] && arandr
[ "$1" != "-a" ] && awesome-font-echo '\uf108' && echo -n ' '
echo "$(i3brightness -print)%"
