#!/bin/bash
### This is only if your location isn't automatically detected, otherwise you can leave it blank.
location="Doha"

[[ "$location" != "" ]] && location="~${location// /+}"

[[ $BLOCK_BUTTON = "1" ]] && st -e popweather

curl -s wttr.in/$location?n > ~/.weatherreport

ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` >/dev/null || exit

#echo -n $(cat ~/.weatherreport | sed '16q;d' | sed -e 's/[^m]*m//g' | grep -o "[0-9]*%" | sort -n | sed -e '$!d' | sed -e "s/^/☔ /g")

#cat ~/.weatherreport | sed '13q;d' | sed -e 's/[^m]*m//g;s/[^0-9]/ /g;s/ /\n/g;/^s*$/d' | grep [0-9] | sort -n | sed -e 1b -e '$!d' | tr '\n' ' ' | awk '{print " ❄️",$1 "°","☀️",$2 "°"}'

#                          Lines from 3rd to 4th        Remove color codes                Cut
V=$(cat ~/.weatherreport | sed -n -e "3,4 p" -e "4 q" | sed "s/\x1B\[[0-9;]*[JKmsu]//g" | cut -c 16-)
S=$(echo "$V" | head -1 | awk '{print tolower($0)}')
W=$(echo "$V" | tail -1 | awk -F'[- ]' '{print $1 $3}')
awesome-font-echo '\uf0c2'
echo " $W"
