#!/bin/bash
O=$(sensors coretemp-isa-0000 -j | jq '.["coretemp-isa-0000"]["Package id 0"]')
T=$(echo "$O" | jq '.["temp1_input"]')
M=$(echo "$O" | jq '.["temp1_max"]')
if [ "$1" != "-a" ]; then
    P=$(printf '%.0f' $(echo "$T/$M*100" | bc -l))
    if [ "$P" -ge "90" ]; then
        awesome-font-echo '\uf12a' red
        echo -n ' '
        awesome-font-echo '\uf2c7' red
    elif [ "$P" -gt "50" ]; then
        awesome-font-echo '\uf2c8'
    elif [ "$P" -gt "40" ]; then
        awesome-font-echo '\uf2c9'
    else
        awesome-font-echo '\uf2ca'
    fi
    echo -n ' '
fi
echo "${T}°C"
