#!/bin/sh

JAILS="$HOME/Jails"
POL_PATH=/mnt/hdd1/Public/Games/windows/playonlinux
[ -d "$POL_PATH" ] || POL_PATH="$JAILS/playonlinux"

LINE='==================================='

info() {
    echo $LINE
    printf '\033[1;34mINFO:\033[0m '
    echo "$@"
    echo $LINE
}

err() {
    {
        echo $LINE
        printf '\033[1m\033[31mERROR:\033[0m '
        echo "$@"
        echo $LINE
    } >&2
}

needed() {
    echo $LINE
    printf '\033[1;33mNEEDED:\033[0m '
    echo "$@"
    echo $LINE
}

mkjail() {
    if [ "$1" = 'playonlinux' ]; then
        J="$POL_PATH"
    else
        J="$JAILS/$1"
    fi
    mkdir -p "$J"
    echo "$J"
}

fire() {
    name="$1"
    shift
    jail=$(mkjail "$name")
    # TODO: --net=none
    firejail \
        --private-tmp \
        --blacklist=/mnt \
        --private="$jail" \
        "$@"
}

list() {
    env QUOTING_STYLE=literal \
        ls -1 "$POL_PATH/.PlayOnLinux/shortcuts" |
        while read -r name; do
            echo "playinjail@$name"
        done

    # maybe https://appimage.github.io/feed.json
    echo 'appjail@Unity3D@https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage'
    echo 'appjail@Zoom@https://github.com/probonopd/Zoom.AppImage/releases/download/stable/Zoom-5.7.31792.0820.glibc2.17-x86_64.AppImage'

    # direct firejail
    echo 'straight2jail@Steam@steam'
}

menu() {
    m=menus-face
    command -v $m >/dev/null || m=dmenu
    P=$({
           list | cut -d '@' -f2
           echo 'Manage PlayOnLinux'
       } | $m -i -l 20)
    case "$P" in
        'Manage PlayOnLinux')
            playinjail ;;
        '')
            return 1;;
        *)
            run "$P";;
    esac
}

winejail() {
    : # TODO
}

playinjail() {
    name="$1"
    [ $# != 0 ] && shift
    if [ "$name" ]; then
        fire playonlinux playonlinux --run "$name" "$@"
    else
        fire playonlinux playonlinux "$@"
    fi
}

appjail() {
    IMGS_DIR="$JAILS/appimages"
    mkdir -p "$IMGS_DIR"

    name="$1"
    url=$(list | grep -m1 "^appjail@$name@" | cut -d '@' -f3)
    img=$(echo "$url" | awk -F/ '{print $NF}')
    img="$IMGS_DIR/$img"

    [ -f "$img" ] || {
        info "Downloading $name AppImage from $url..."
        cd "$IMGS_DIR" && wget "$url"
    }
    [ -x "$img" ] || chmod +x "$img"

    fire "$name" --appimage --noprofile "$img"
}

straight2jail() {
    name="$1"
    shift
    cmd=$(list | grep -m1 "^straight2jail@$name@" | cut -d '@' -f3)
    # https://wiki.archlinux.org/title/Firejail#Graphical_applications_hang_on_start_with_AMDGPU
    # case "$name" in
    #     Steam) export DRI_PRIME=1 ;;
    # esac
    fire "$name" "$cmd"
}

run() {
    name=$(list | cut -d '@' -f2 | grep -i "$1")
    kind=$(list | grep "@$name" | cut -d '@' -f1)

    f="$2"
    if [ "$kind" = 'playinjail' ] && [ -f "$f" ]; then
        jail=$(mkjail "playonlinux")
        fname=$(basename "$f")
        tmpf="$jail/tmpfile"
        mkdir -p "$tmpf"
        tmpf="$tmpf/$fname"

        cp "$f" "$tmpf"
        "$kind" "$name" "$HOME/tmpfile/$fname"

        if ! cmp "$f" "$tmpf"; then
            d=$(date '+%Y%m%d-%H%M%s')
            mv "$f" "$f-$d.bak"
            mv "$tmpf" "$f"
            chmod -x "$f"
        else
            rm "$tmpf"
        fi
    else
        "$kind" "$name"
    fi
}

main() {
    # command -v dash >/dev/null && export SHELL=dash

    if [ $# -gt 0 ]; then
        cmd="$1"
        shift
        case "$cmd" in
            list)   list | tr '@' ' '   ;;
            pol)    playinjail "$@"     ;;
            *)      run     "$cmd" "$@" ;;
        esac
    else
        menu
    fi
}

main "$@"
