#!/bin/sh

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk/bin/
JSWEET="$HOME/GoodStuff/jsweet/transpiler/target/jsweet-transpiler-2.3.6-SNAPSHOT-jar-with-dependencies.jar"
if [ $# = 1 ] && [ -d "$1" ]; then
    java -jar "$JSWEET" -i "$@"
else
    java -jar "$JSWEET" "$@"
fi
