#!/bin/python3

import sh
import os
import sys

argv = sys.argv
HOME = os.getenv("HOME")

sys.path.append(os.getenv("DOTFILES_DIR") + '/configs')
from hotkeys import bindings

class Binding:
    def __init__(self, t):
        if len(t) == 3:
            self.doc  = t[0]
            self.keys = t[1]
            self.cmd  = t[2]
        elif len(t) == 2:
            self.doc  = None
            self.keys = t[0]
            self.cmd  = t[1]

def get_doc():
    for b in bindings:
        b = Binding(b)
        if b.doc is not None:
            yield ('%-40s: %s' % (b.keys, b.doc))

def run(keys):
    for b in bindings:
        b = Binding(b)
        if b.keys == keys:
            os.system(b.cmd)

def gen_sxhkdrc():
    with open(f"{HOME}/.config/sxhkd/sxhkdrc", "w") as outfile:
        outfile.write("# DO NOT EDIT!\n")
        outfile.write(f"# Generated by %s at %s\n" % (__file__, sh.date().strip()))
        for b in bindings:
            if b.doc is not None:
                outfile.write("# %s\n" % b.doc)
            outfile.write("%s\n\t%s\n\n" % (b.keys, b.cmd))
    sh.pkill("-USR1", "-x", "sxhkd")

def main(args):
    if len(args) > 0:
        if args[0] == "-d":
            for d in get_doc():
                print(d)
        elif args[0] == "-r":
            run(args[1])
        elif args[0] == "-g":
            gen_sxhkdrc()

if __name__ == "__main__":
    main(argv[1:])
