#!/bin/bash
L=$(setxkbmap -query | sed -En 's/layout:\s*(.+)/\1/p' 2>/dev/null)
if [[ "$1" != "-v" ]]; then
    if [[ "$L" = "us" ]]; then
        L=ar
    else
        L=us
    fi
    setxkbmap -layout $L
    pkill -RTMIN+$I3BLOCKS_SIG_LANG i3blocks
fi
echo $L | tee ~/.lang
