#!/bin/bash
L="$1"
[[ "$L" = '' ]] && {
    echo 'ERROR: No language selected'
    exit 1
}
setxkbmap -layout $L
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
pkill -RTMIN+$I3BLOCKS_SIG_LANG i3blocks
echo $L
