#!/bin/sh

run() {
    TYPE=$(echo "$1" | sed -En 's/\s*(.+): .+/\1/p')
    RUN=$(echo "$1" | sed -En 's/.+: (.+)/\1/p')

    [ ! "$RUN" ] && RUN="$TYPE"
    [ ! "$RUN" ] && return 1

    case "$TYPE" in
        power)
            dmenupower "$RUN";;
        shortcuts)
            RUN=$(echo "$RUN" | awk '{print $1}')
            msg=$(eval "$DOTFILES_DIR/configs/i3.conf.gen.sh" -r "$RUN")
            i3-msg "$msg";;
        *)
            launcherhelperpy inc "$RUN"
            if launcherhelperpy istui "$RUN"; then
                exec theterm "$RUN"
            else
                exec "$RUN"
            fi;;
    esac
}

main() {
    case "$1" in
        run)    run "$2";;
        istui)  launcherhelperpy istui  "$2";;
        isgame) launcherhelperpy isgame "$2";;
        clear)  launcherhelperpy clear;;
        '')     launcherhelperpy special;;
    esac
}

main "$@"
