#!/bin/sh

run() {
    TYPE=$(echo "$1" | cut -f 1 -d ':' | xargs)
    RUN=$(echo "$1" | cut -f 1 -d ':' --complement | xargs)

    # echo "$TYPE"; echo "$RUN"

    [ ! "$RUN" ] && RUN="$TYPE"
    [ ! "$RUN" ] && return 1

    case "$TYPE" in
        power)
            dmenupower "$RUN";;
        shortcuts)
            RUN=$(echo "$RUN" | awk '{print $1}')
            msg=$(eval "$DOTFILES_DIR/configs/i3.conf.gen.sh" -r "$RUN")
            i3-msg "$msg";;
        bar)
            bar gui;;
        *)
            if command -v "$RUN" >/dev/null; then
                launcherhelperpy inc "$RUN"
                if launcherhelperpy istui "$RUN"; then
                    exec theterm "$RUN"
                else
                    exec "$RUN"
                fi
            fi;;
    esac
}

main() {
    case "$1" in
        run)    run "$2";;
        istui)  launcherhelperpy istui  "$2";;
        isgame) launcherhelperpy isgame "$2";;
        clear)  launcherhelperpy clear;;
        '')     launcherhelperpy special;;
    esac
}

main "$@"
