#!/bin/bash

newvol="pkill -RTMIN+$I3BLOCKS_SIG_VOLU i3blocks"

V="$2"
case "$1" in
	"up")       pamixer --allow-boost -i "$V" ; $newvol ;;
	"down")     pamixer --allow-boost -d "$V" ; $newvol ;;
	"mute")     pamixer --allow-boost -t ; $newvol ;;
	"truemute") pamixer --allow-boost -m ; $newvol ;;
	"stop")     cmus-remote --stop ;;
	"pause")    cmus-remote --pause ;;
	"forward")  cmus-remote --seek +"$V" ;;
	"back")     cmus-remote --seek -"$V" ;;
	"next")     cmus-remote --next ;;
	"prev")     cmus-remote --prev ;;
	"replay")   cmus-remote --seek 0 ;;
esac
