#!/bin/bash

newvol="pkill -RTMIN+4 i3blocks"

case "$1" in
	"up") pamixer --allow-boost -i "$2" ; $newvol ;;
	"down") pamixer --allow-boost -d "$2" ; $newvol ;;
	"mute") pamixer --allow-boost -t ; $newvol ;;
	"truemute") pamixer --allow-boost -m ; $newvol ;;
	"stop") cmus-remote --stop ;;
	"pause") cmus-remote --pause ;;
	"forward") cmus-remote --seek +"$2" ;;
	"back") cmus-remote --seek -"$2" ;;
	"next") cmus-remote --next ;;
	"prev") cmus-remote --prev ;;
	"replay") cmus-remote --seek 0 ;;
esac
