#!/bin/sh

pgrep i3lock && {
    echo Already locked
    exit 0
}

"$(dirname "$0")/lang" us &

[ "$FONT" ] || FONT='sans-serif'
COLOR='ffffffff'

# using picom for blur and opacity
i3lock \
     -e -f -c 000000 \
     --clock \
     --indicator \
     --time-str '%H:%M' \
     --date-str '%Y.%m.%d' \
     --time-font "$FONT" \
     --date-font "$FONT" \
     --layout-font "$FONT" \
     --verif-font "$FONT" \
     --wrong-font "$FONT" \
     --greeter-font "$FONT" \
     --time-size 40 \
     --date-size 20 \
     --time-align 0 \
     --date-align 0 \
     --time-color "$COLOR" \
     --date-color "$COLOR" \
     --ring-color ffffffff \
     --pass-media-keys \
     --pass-screen-keys \
     --pass-power-keys \
     --pass-volume-keys
