#!/bin/bash

function blur-convert {
    if [ -f /usr/bin/convert ]; then
        convert $1 -blur 0x09 $2
        echo $2
    else
        echo $1
    fi
}

function blur-ffmpeg {
    if [ -f /usr/bin/ffmpeg ]; then
        ffmpeg -loglevel quiet -y -i $1 -vf "scale=iw/2:-1, gblur=9, scale=2*iw:-1" $2
        echo $2
    else
        echo $1
    fi
}

function blur {
    #pgrep -x dunst && notify-send -i $DOTFILES_SCRIPTS/lock.png "Locking computer..."
    #blur-convert $@
    blur-ffmpeg $@
}

function gen-bg {
    W=~/.cache/lock-base.png
    O=~/.cache/lock-lock.png
    rm -f "$W" "$O"
    scrot -m -z "$W"
    blur $W $O
}

function gen-bg-simple {
    W="$DOTFILES_DIR/configs/wall"
    O="$DOTFILES_DIR/configs/wall-blur"
    if [ ! -f $O ] || [ $O -ot $W ]; then
        echo $(blur $W $O)
    else
        echo $O
    fi
}

lang-set us &>/dev/null
#audioctl stop &>/dev/null

B=$(gen-bg)
#B=$(gen-bg-simple)

[[ "$FONT" == '' ]] && FONT='DejaVu Sans Mono'
if imgtoobright "$B"; then
    COLOR='000000ff'
else
    COLOR='ffffffff'
fi
X=960
Y=800

i3lock \
    -e -f -c 000000 -i $B \
    --clock \
    --indicator \
    --timestr '%H:%M' \
    --datestr '%Y-%m-%d' \
    --time-font "$FONT" \
    --date-font "$FONT" \
    --timesize 70 \
    --datesize 50 \
    --timepos "$X:$Y" \
    --datepos "$X:$((Y+70))" \
    --timecolor "$COLOR" \
    --datecolor "$COLOR"

# In five seconds, turn off display unless key press in last 4 seconds.
#sleep 5 && [[ 4000 -lt $(xssstate -i) ]] &&  pgrep -x i3lock && xset dpms force off
