#!/bin/bash

function strbetweenlines {
    A="$1"
    B="$2"
    P=0
    while read line; do
        if echo "$line" | grep -q "$B"; then
            P=0
        fi
        [[ "$P" = "1" ]] && echo "$line"
        if echo "$line" | grep -q "$A"; then
            P=1
        fi
    done
}

URL='https://genius.com/Edith-piaf-la-foule-lyrics'
curl "$URL" | \
    strbetweenlines '<div class=\"lyrics\">' '<!--/sse-->' | \
    sed 's/<!--sse-->//g' | \
    sed 's/\s*<p>/ /g' | \
    sed 's/<\/p>//g' | \
    sed 's/<br>//g'
