#!/bin/bash

function strbetweenlines {
    A="$1"
    B="$2"
    P=0
    while read line; do
        if echo "$line" | grep -q "$B"; then
            P=0
        fi
        [[ "$P" = "1" ]] && echo "$line"
        if echo "$line" | grep -q "$A"; then
            P=1
        fi
    done
}

Q="$@"

[[ "$Q" = '' ]] && {
    C="$(cmus-remote -Q)"
    T=$(echo "$C" | sed -rn 's/tag title (.+)/\1/p')
    A=$(echo "$C" | sed -rn 's/tag artist (.+)/\1/p')
    Q="$T $A"
}

Q=$(echo "$Q" | sed 's/ /+/g')
U=$(curl -s "https://search.azlyrics.com/search.php?q=$Q")
U=$(echo "$U" | sed -rn 's/.* 1\. <a href="(.+).html" .+/\1.html/p')
O=$(lynx -dump "$U")
S=$(echo "$O" | strbetweenlines 'Print' 'Submit Corrections')
[[ "$S" = '' ]] && echo "Error on Q='$Q', U='$U'" && echo "$O" && exit
echo "$S"


