#!/bin/bash

[ -z "$MENU_INTERFACE" ] && MENU_INTERFACE='dmenu'

LANGUAGE=$(lang-get)
lang-set us >/dev/null &

case $MENU_INTERFACE in
    dmenu)
        dmenu "$@"
        dmenufixfocus 2>/dev/null;;
    rofi)
        cmd="rofi -width 50 -dmenu -font '$FONT_MONO 18'"
        args=("$@")
        inc=0
        lines=10
        for ((i=0; i < ${#args[@]}; ++i)); do
            a=${args[i]}
            [[ $a ==  '-fn' ]] || \
                [[ $a ==  '-nb' ]] || \
                [[ $a ==  '-nf' ]] || \
                [[ $a ==  '-sb' ]] || \
                [[ $a ==  '-sf' ]] \
                    && args[i]='' \
                    && args[i+1]='' \
                    && inc=1

            [[ $a == '-l' ]] \
                && lines=${args[i+1]} \
                && args[i]='' \
                && args[i+1]='' \
                && inc=1

            [[ ${args[i]} != '' ]] \
                && cmd="$cmd '${args[i]}'"

            [[ $inc == 1 ]] \
                && let ++i \
                && inc=0 \
                && [[ ${args[i]} != '' ]] \
                && cmd="$cmd '${args[i]}'"
        done
        eval "$cmd -lines $lines";;
    fzf)
        cmd='fzfp --nopv'
        args=("$@")
        inc=0
        for ((i=0; i < ${#args[@]}; ++i)); do
            a=${args[i]}
            [[ $a ==  '-l' ]] || \
                [[ $a ==  '-fn' ]] || \
                [[ $a ==  '-nb' ]] || \
                [[ $a ==  '-nf' ]] || \
                [[ $a ==  '-sb' ]] || \
                [[ $a ==  '-sf' ]] \
                    && args[i]='' \
                    && args[i+1]='' \
                    && inc=1

            [[ $a == '-p' ]] \
                && args[i]='--prompt' \
                && args[i+1]="${args[i+1]} > " \
                && inc=1

            [[ ${args[i]} != '' ]] \
                && cmd="$cmd '${args[i]}'"

            [[ $inc == 1 ]] \
                && let ++i \
                && inc=0 \
                && [[ ${args[i]} != '' ]] \
                && cmd="$cmd '${args[i]}'"
        done
        TMPI="/tmp/__menui_$$"
        TMPO="/tmp/__menuo_$$"
        rm -f "$TMPI" "$TMPO"
        while read -r line; do
            echo "$line" >> "$TMPI"
        done
        theterm -a '-c __floatme__ -g 60x35' "cat '$TMPI' | $cmd > '$TMPO'"
        cat "$TMPO"
        rm -f "$TMPI" "$TMPO";;
esac

lang-set "$LANGUAGE" >/dev/null
