#!/bin/sh

# TODO: move to personal

ENC=/mnt/hdd1/Private-enc/
DEC=/mnt/hdd1/Private/

mountpoint -q /mnt/hdd1 || {
    mkdir -p /mnt/hdd1
    sudo mount /dev/sdb1 /mnt/hdd1
    [ -d "$ENC" ] || {
        # if the expect directory is not there,
        # then this is not supposed to run here.
        sudo umount /mnt/hdd1
        exit
    }
}

case "$1" in
    -u)
        mountpoint -q "$HOME/M"      && fusermount -u "$HOME/M"
        mountpoint -q "$DEC"         && fusermount -u "$DEC"
        mountpoint -q "$HOME/.cache" && fusermount -u "$HOME/.cache"
        ;;

    -m)
        printf 'Enter password: '
        read -r -s p
        printf '\nLoading...\n'
        mountpoint -q "$DEC" || {
            echo "$p" | encfs -S "$ENC" "$DEC"
        }
        mountpoint -q "$HOME/.cache" || {
            [ -d "$HOME/.cache-enc/" ] && {
                rm -rf ~/.cache && mkdir -p ~/.cache
                echo "$p" | sudo encfs --public -S "$HOME/.cache-enc/" "$HOME/.cache"
            }
        }
        ;;

    '')
        theterm \
            -a '-c __floatme__ -g 40x5' \
            "echo;echo;exec '$0' -m"
        ;;
esac
