#!/bin/sh

# start the daemon
mpd 2>/dev/null >/dev/null

# start the notification daemon
pgrep mpd-notificatio >/dev/null || {
    nohup mpd-notification &
}

case "$1" in
    --find)
        song="$(mpc search any '' | fzf --reverse)"
        [ "$song" ] && {
            mpc insert "$song"
            mpc next
        };;
    *)
        exec ncmpcpp "$@";;
esac
