#!/bin/sh

mpd 2>/dev/null >/dev/null

case "$1" in
    --find)
        song="$(mpc search any '' | fzf --reverse)"
        [ "$song" ] && {
            mpc insert "$song"
            mpc next
        };;
    *)
        exec ncmpcpp "$@";;
esac
