#!/bin/sh

if [ "$DOTFILES_DIR" ]; then
    D="$DOTFILES_DIR"
else
    D="$PWD"
fi

H="$HOME"

C='\033[1m\033[34m' # info color
E='\033[1m\033[31m' # error color
R='\033[0m'         # reset color

INSTALLED=

get_installed() {
    [ "$INSTALLED" ] ||
        INSTALLED=$( (pacman -Qet && pacman -Qm) | awk '{print $1}')
    echo "$INSTALLED"
}

cmd_exists() {
    command -v "$1" >/dev/null
}

ispi() {
    grep -q 'Raspberry Pi' /sys/firmware/devicetree/base/model 2>/dev/null
}

isubuntu() {
    cmd_exists apt-get
}

isarch() {
    cmd_exists pacman
}

istiny() {
    ispi
}

info() {
    printf "${C}INFO:${R} %s\n" "$@"
}

err() {
    printf "${E}ERROR:${R} %s\n" "$@" >&2
}

if ispi; then
    CATEGORIES="pi"
elif isubuntu; then
    CATEGORIES="ubuntu"
else
    CATEGORIES="base base-gui additions themostsignificant devel electronics games"
fi

export TINY=$(istiny && echo t)

# systemd service to run lockscreen on suspend
lock_service() {
    echo "[Unit]
Description = Lock screen when going to sleep/suspend
Before=sleep.target
Before=suspend.target

[Service]
User=%i
Type=forking
Environment=DISPLAY=:0
ExecStart=$D/scripts/lockscreen
TimeoutSec=infinity
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sleep.target
WantedBy=suspend.target" |
        sudo tee /etc/systemd/system/wakelock@.service >/dev/null
    sudo systemctl enable "wakelock@$USER.service"
}

# symlink configs
dots_link() {
    lnnn() {
        TODIR=$(dirname "$2")
        mkdir -p "$TODIR"
        rm -rf "$2" 2>/dev/null
        ln -s "$1" "$2"
    }

    lnnn "$D/configs/i3.conf"             "$H/.config/i3/config"
    lnnn "$D/configs/bspwmrc"             "$H/.config/bspwm/bspwmrc"
    lnnn "$D/configs/dunstrc"             "$H/.config/dunst/dunstrc"
    lnnn "$D/configs/fish-config.fish"    "$H/.config/fish/config.fish"
    lnnn "$D/configs/fonts.conf"          "$H/.config/fontconfig/fonts.conf"
    lnnn "$D/configs/mpd.conf"            "$H/.config/mpd/mpd.conf"
    lnnn "$D/configs/ncmpcpp.conf"        "$H/.config/ncmpcpp/config"
    lnnn "$D/configs/sxiv-key-handler.sh" "$H/.config/sxiv/exec/key-handler"
    lnnn "$D/configs/sxiv-image-info.sh"  "$H/.config/sxiv/exec/image-info"
    lnnn "$D/configs/picom.conf"          "$H/.config/picom.conf"
    lnnn "$D/configs/user-dirs.dirs"      "$H/.config/user-dirs.dirs"
    lnnn "$D/configs/mednafen.cfg"        "$H/.mednafen/mednafen.cfg"
    lnnn "$D/configs/bashrc.sh"           "$H/.bashrc"
    lnnn "$D/configs/blerc.sh"            "$H/.config/blesh/init.sh"
    lnnn "$D/configs/profile"             "$H/.profile"
    lnnn "$D/configs/profile"             "$H/.bash_profile"
    lnnn "$D/configs/profile"             "$H/.xprofile"
    lnnn "$D/configs/xinitrc.sh"          "$H/.xinitrc"
    lnnn "$D/configs/Xresources"          "$H/.Xresources"
    lnnn "$D/configs/Xmodmap"             "$H/.Xmodmap"
    lnnn "$D/configs/tmux.conf"           "$H/.tmux.conf"
    lnnn "$D/configs/emacs-init.el"       "$H/.emacs"
    lnnn "$D/configs/nm-dmenu.ini"        "$H/.config/networkmanager-dmenu/config.ini"
    lnnn "$D/configs/gtk-icons.theme"     "$H/.icons/default/index.theme"
    lnnn "$D/configs/gtk3-settings.ini"   "$H/.config/gtk-3.0/settings.ini"
    lnnn "$D/configs/gtk3.css"            "$H/.config/gtk-3.0/gtk.css"
    lnnn "$D/configs/gtk2rc"              "$H/.gtkrc-2.0"
    lnnn "$D/configs/gotop.conf"          "$H/.config/gotop/gotop.conf"
    lnnn "$D/configs/gotop-layout"        "$H/.config/gotop/mylayout"
    lnnn "$D/configs/arduino-cli.yaml"    "$H/.arduino15/arduino-cli.yaml"
    lnnn "$D/configs/stpv-config.sh"      "$H/.config/stpv/config.sh"
    lnnn "$D/configs/nanorc"              "$H/.nanorc"
    lnnn "$D/configs/sxhkdrc"             "$H/.config/sxhkd/sxhkdrc"
}

# update dots configs
dots_update() {
    "$D/configs/onboard-gsettings.sh"
    dots_link
}

# installs everything
dots_install() {
    info "Installing Naheel's dotfiles..."

    # makes a 'main' user and keep it passwordless
    # used probably for docker
    QUICK=
    [ "$1" = '--quick' ] && {
        QUICK="$1"
        shift
    }

    if [ ! "$QUICK" ]; then
        echo "This might destroy you're system. Are you sure you want to install it? [yes/No]"
        read -r ans
        [ "$ans" != yes ] && return 1
    fi

    PACS="$*"

    mkuser() {
        echo 'Enter username:'
        read -r user
        useradd -m -g wheel "$user"
        echo 'Enter password:'
        passwd "$user"
        sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' \
            /etc/sudoers 2>/dev/null
    }

    ARCH_ROOT_UPDATED=
    [ "$(whoami)" = root ] && {
        # double check keyring, updates, sudo
        if isarch; then
            info "Upgrading the system"
            pacman --noconfirm -Sy &&
                pacman --noconfirm -S archlinux-keyring
            pacman --noconfirm -Syu &&
                pacman --noconfirm --needed -S sudo &&
                ARCH_ROOT_UPDATED=1
        fi
        if [ ! "$QUICK" ]; then
            info "Looks like you're running as root!"
            echo '1) Create a new user'
            echo '2) Or login to existing one'
            printf 'Choice: [1/2] '
            read -r ans
            case "$ans" in
                1) mkuser;;
                2) echo 'Enter username:' && read -r user;;
                *) return 1;;
            esac
        else
            user=main
            [ -d /home/main ] ||
                useradd -m -g wheel "$user" &&
                    passwd -d "$user"
        fi

        DEST="/home/$user/.dotfiles"
        rm -rf "$DEST" &&
            cp -r "$D" "$DEST" &&
            chown -R "$user" "$DEST" && {
                sed -i 's/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers
                sudo -u "$user" sh -c "cd $DEST && ./install.sh $QUICK $PACS"
            }

        echo 'Now log in to your user account'
        echo "\$ su $user"
        return
    }

    info "Setting up sudo"
    # allow no password sudo
    sudo sed -i 's/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers
    # add some commands to no password sudo if needed
    #  `sudo updatedb` is needed for `locate`
    #  `sudo encfs` is needed when using the `--public` option
    nopass='%wheel ALL=(ALL) NOPASSWD: /usr/bin/updatedb,/usr/bin/encfs,/usr/bin/chmod a+rw /sys/class/backlight/intel_backlight/brightness,/usr/bin/mount,/usr/bin/umount'
    sudo grep -q "$nopass" /etc/sudoers ||
        echo "$nopass" | sudo tee -a /etc/sudoers

    info "Upgrading the system"
    if isubuntu; then
        sudo apt update --yes
        sudo apt upgrade --yes
    elif [ "$ARCH_ROOT_UPDATED" != 1 ]; then
        sudo grep -q '^\[multilib\]' /etc/pacman.conf ||
            printf '[multilib]\nInclude = /etc/pacman.d/mirrorlist\n' | sudo tee -a /etc/pacman.conf
        sudo pacman --noconfirm -Syu
    fi

    info "Install packages"
    [ "$PACS" ] || PACS='base'
    pkg_install "$PACS"

    info "Setting up systemd services"
    sudo systemctl enable NetworkManager
    sudo systemctl enable org.cups.cupsd
    lock_service

    info "Setting up sensors"
    sudo sensors-detect --auto
    sudo modprobe eeprom

    info "Setting up keyring"
    # https://wiki.archlinux.org/index.php/GNOME/Keyring#Without_a_display_manager
    f=/etc/pam.d/login
    grep -Eq 'auth\s+optional\s+pam_gnome_keyring.so' $f ||
        sudo sed -i "s/account/auth       optional     pam_gnome_keyring.so\naccount/" $f
    grep -Eq 'session\s+optional\s+pam_gnome_keyring.so auto_start' $f ||
        echo 'session    optional     pam_gnome_keyring.so auto_start' | sudo tee -a $f >/dev/null

    f=/etc/pam.d/passwd
    grep -Eq 'password\s+optional\s+pam_gnome_keyring.so' $f ||
        echo 'password	optional	pam_gnome_keyring.so' | sudo tee -a $f >/dev/null

    info "Setting configs"
    dots_update

    info "Setting the path"
    echo "#!/bin/sh
export DOTFILES_DIR=$D
export DOTFILES_SCRIPTS=\"\$DOTFILES_DIR/scripts\"
export PATH=\"\$PATH:\$DOTFILES_SCRIPTS\"
" > "$HOME/.dotfiles-exports"
    chmod +x "$HOME/.dotfiles-exports"
    sudo mkdir /mnt/hdd1/ \
         /mnt/usb1/ \
         /mnt/usb2/ \
         /mnt/usb3/ \
         /mnt/usb4/ \
         /mnt/usb5/

    info "Installing fish complete"
    sudo mkdir -p '/usr/share/fish/completions/'
    sudo cp -f "$D/scripts/ndots-complete.fish" \
         '/usr/share/fish/completions/ndots.fish'

    info "Starting Emacs daemon"
    emacs --daemon

    # disallow no password sudo
    [ "$QUICK" ] ||
        sudo sed -i 's/%wheel ALL=(ALL) NOPASSWD: ALL/# %wheel ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers

    echo 'DONE!!!'
}

# install a package ($2) given its tag ($1)
pkg_install_from() {
    if [ "$1" = '--test' ]; then
        doit() { false; }
        shift
    else
        doit() { true; }
    fi
    if [ "$1" = '--uninstall' ]; then
        install=
        shift
    else
        install=1
    fi
    tag="$1"
    shift
    case "$tag" in
        pacman)
            if doit; then
                if [ "$install" ]; then
                    sudo pacman --noconfirm --needed -S "$1"
                else
                    sudo pacman -R "$1"
                fi
            fi;;

        aur)
            if doit; then
                if [ "$install" ]; then
                    get_installed | grep -q "^$1$" &&
                        echo "$1 is already installed" && return
                    yay -S --noconfirm --needed "$1"
                else
                    yay -R "$1"
                fi
            fi;;

        aur_manual)
            if doit; then
                if [ "$install" ]; then
                    helper="$1"
                    cmd_exists "$helper" || (
                        cd /tmp || return 1
                        rm -rf /tmp/"$helper"*
                        curl -sO https://aur.archlinux.org/cgit/aur.git/snapshot/"$helper".tar.gz &&
                            tar -xvf "$helper".tar.gz &&
                            cd "$helper" &&
                            makepkg --noconfirm -si
                        cd /tmp || return 1)
                else
                    sudo rm "$(which "$helper")"
                fi
            fi;;

        apt)
            if doit; then
                if [ "$install" ]; then
                    ppa="$2"
                    if echo "$ppa" | grep -q '^ppa:'; then
                        sudo add-apt-repository "$ppa"
                        sudo apt update
                    fi
                    sudo apt install --yes "$1"
                else
                    sudo apt remove --yes "$1"
                fi
            fi;;

        snap)
            if doit; then
                if [ "$install" ]; then
                    sudo snap install "$1" --classic --channel stable
                else
                    sudo snap remove "$1"
                fi
            fi;;

        pip)
            if doit; then
                if [ "$install" ]; then
                    sudo pip3 install --upgrade "$1"
                else
                    sudo pip3 uninstall "$1"
                fi
            fi;;

        npm)
            if doit; then
                if [ "$install" ]; then
                    sudo npm install -g "$1"
                else
                    sudo npm uninstall -g "$1"
                fi
            fi;;

        go)
            if doit; then
                if [ "$install" ]; then
                    cmd_exists "$1" || go get -v -u "$2"
                else
                    err 'Not implementd' # TODO
                fi
            fi;;

        git_manual)
            if doit; then
                pac="$1"
                link="$2"
                if [ "$install" ]; then
                    dir=$(mktemp -d)
                    git clone --depth 1 "$link" "$dir" &&
                        cd "$dir" &&
                        sudo make && sudo make install &&
                        cd /tmp && sudo rm -rf "$dir" || return 1
                else
                    bin=$(which "$pac")
                    sudo rm "$bin"
                fi
            fi;;

        git|suckless)
            if doit; then
                pac="$1"
                link="$2"
                if [ "$install" ]; then
                    if [ "$tag" = suckless ]; then
                        patch="$D/configs/$pac-patch.diff"
                        sudo pacgit -S --patch "$patch" "$pac" "$link"
                    else
                        sudo pacgit -S "$pac" "$link"
                    fi
                else
                    sudo pacgit -R "$pac" "$link"
                fi
            fi;;

        func)
            case "$1" in
                blesh)
                    if doit; then
                        if [ "$install" ]; then
                            if [ -d "$HOME/.local/share/blesh" ]; then
                                echo 'blesh is already installed'
                            else
                                cd /tmp &&
                                    git clone --recursive https://github.com/akinomyoga/ble.sh.git &&
                                    make -C ble.sh install PREFIX="$HOME/.local"
                                rm -rf ble.sh
                            fi
                        else
                            rm -rf "$HOME/.local/share/blesh"
                        fi
                    fi;;

                tpm)
                    if doit; then
                        if [ "$install" ]; then
                            [ -d "$HOME/.tmux/plugins/tpm" ] && {
                                echo 'TPM is already installed'
                                return 0
                            }
                            rm -rf "$HOME/.tmux"
                            mkdir -p "$HOME/.tmux/plugins/tpm"
                            git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
                            tmux source "$HOME/.tmux.conf" ||:
                        else
                            rm "$HOME/.tmux/plugins/tpm"
                        fi
                    fi;;

                blackarch)
                    if doit; then
                        if [ "$install" ]; then
                            grep -q '^\[blackarch\]' /etc/pacman.conf && {
                                echo 'Blackarch is already installed'
                                return 0
                            }
                            cd /tmp || return 1
                            curl -O https://blackarch.org/strap.sh || return 1
                            test "$(sha1sum strap.sh | cut -d ' ' -f1)" = \
                                 9c15f5d3d6f3f8ad63a6927ba78ed54f1a52176b || {
                                err 'Failed verifying blackarch strap script hash'
                                return 1
                            }
                            chmod +x strap.sh && sudo ./strap.sh || return 1
                            rm -rf /tmp/strap.sh
                            sudo sed -i 's/# Server/Server/g' /etc/pacman.d/blackarch-mirrorlist
                        else
                            err 'Not implementd' # TODO
                        fi
                    fi;;

                chafa)
                    if doit; then
                        if [ "$install" ]; then
                            cmd_exists chafa && {
                                echo 'chafa is already installed'
                                return 0
                            }
                            cd /tmp || return 1
                            version=1.4.1-1
                            curl -sL "https://hpjansson.org/chafa/releases/static/chafa-$version-x86_64-linux-gnu.tar.gz" | tar xz
                            sudo mv "chafa-$version-x86_64/chafa" /bin/chafa
                            rm -r "chafa-$version-x86_64"
                        else
                            sudo rm "$(which chafa)"
                        fi
                    fi;;

                *)
                    err "No special function '$1'" && return 1;;
            esac;;

        *)
            err "Unknow package tag '$tag'" && return 1;;
    esac
}

# gets the list of packages from tables
pkg_load_tables() {
    cd "$D/packages" || {
        err 'No packages tables found'
        exit 1
    }
    if [ $# != 0 ]; then
        files="$*"
        [ "$files" = all ] &&
            files="$CATEGORIES"
    else
        files="base base-gui"
    fi
    for f in $files; do
        [ -f "$f.org" ] || {
            err "Unknown package group '$f'"
            return 1
        }
        tail -n +3 "$f.org" | sed 's/|/ /g;s/  */ /g'
    done
}

# install list of packages
pkg_install_pacs() {
    if [ "$1" = '--uninstall' ]; then
        uninstall=1
        shift
    else
        uninstall=
    fi
    pacs="$1"
    total=$(echo "$pacs" | wc -l)
    i=1
    echo "$pacs" | while read -r tag pac link des; do
        printf "($i/$total) ${C}INSTALLING${R} $pac ${C}FROM${R} %s, %s\n" "$tag" "$des"
        if [ -n "$uninstall" ]; then
            pkg_install_from --uninstall "$tag" "$pac" "$link" ||
                err "Failed uninstalling '$pac'"
        else
            pkg_install_from "$tag" "$pac" "$link" ||
                err "Failed installing '$pac'"
        fi
        i=$((i+1))
        echo "-----------------------------"
    done
}

# update git-based packages
pkg_update_git_pacs() {
    info 'Checking for updates...'
    pacs=$(pkg_load_tables all | while read -r tag pac link des; do
               if reason=$(pkg_git_needs_update "$tag" "$pac" "$link"); then
                   echo "$tag $pac $link $reason"
               fi
           done)
    if [ "$pacs" ]; then
        echo 'Packages need to be updated:'
        echo "$pacs" | while read -r _ pac link reason; do
            echo "$pac from $link, $reason"
        done
        echo
        pkg_install_pacs "$pacs"
    else
        echo 'No updates found'
    fi
}

# install a package from the packages tables
pkg_install() {
    if [ "$1" = '--uninstall' ]; then
        uninstall=1
        shift
    else
        uninstall=
    fi

    if [ $# = 0 ]; then
        err 'Select a package to install'
        exit 1
    fi

    case "$1" in
        -f|--from)
            case "$2" in
                pacman|aur|aur_manual|pip|pip2|npm|go|git|apt|snap)
                    tag="$2"
                    pac="$3"
                    link="$4"
                    [ ! "$link" ] && link="$pac"
                    if [ -n "$uninstall" ]; then
                        pkg_install_from --uninstall "$tag" "$pac" "$link"
                    else
                        pkg_install_from "$tag" "$pac" "$link"
                    fi;;
                *)
                    err "Unknown installer '$2'"
                    exit 1
            esac
            return;;
    esac

    if [ "$1" = dots ]; then
        if [ -n "$uninstall" ]; then
            err "Uninstalling dots is not implemented"
            return 1
        fi
        shift
        dots_install "$@"
        return
    fi

    pacs=$(pkg_load_tables all)
    pacs=$(for pac in "$@"; do
               echo "$pacs" | grep -E ".+ $pac .+" | head -n 1
           done)

    if [ "$pacs" ]; then
        pacs_min=$(echo "$pacs" | grep "$(echo "$*" | tr ' ' '\n')" |
                       cut -d ' ' -f 3 | tr '\n' ' ')
        info "Installing packages $pacs_min"
    else
        pacs=$(pkg_load_tables "$@") || {
            err 'Choose either packages groups of packages'
            exit 1
        }
        info "Installing packages groups from $*"
    fi

    if [ -n "$uninstall" ]; then
        pkg_install_pacs --uninstall "$pacs"
    else
        pkg_install_pacs "$pacs"
    fi
}

list_all() {
    DES=
    GR=all
    if [ "$1" = -d ]; then
        DES=1
        shift
    fi
    if [ "$1" ]; then
        GR="$1"
    else
        if [ $DES ]; then
            printf 'dots\tsetup a new machine\n'
        else
            echo "dots"
        fi
        for c in $CATEGORIES; do
            if [ $DES ]; then
                printf '%s\tpackage group\n' "$c"
            else
                echo "$c"
            fi
        done
    fi
    if [ "$GR" = groups ]; then
        if [ $DES ]; then
            printf 'all\tall package groups\n'
        else
            echo all
        fi
        for c in $CATEGORIES; do
            if [ $DES ]; then
                printf '%s\tpackage group\n' "$c"
            else
                echo "$c"
            fi
        done
    else
        pkg_load_tables "$GR" | while read -r _ pac _ des; do
            if [ $DES ]; then
                printf '%s\t%s\n' "$pac" "$des"
            else
                echo "$pac"
            fi
        done
    fi
}

update_repo() {
    cd "$D" || return 1
    # if is git repo
    if git rev-parse --git-dir > /dev/null 2>&1; then
        git pull origin master
    else
        dir=$(mktemp -d)
        git clone https://github.com/Naheel-Azawy/naheel-dotfiles.git "$dir" &&
            rm -rf "$D" &&
            mv "$dir" "$D" &&
            info 'Dots repo updated successfully'
    fi
}

help() {
    BIN=$(basename "$0")
    echo "usage: $BIN COMMAND [OPTIONS]"
    echo 'Commands:'
    echo ' install   Install a (listed package), (package group), or "dots"'
    echo ' uninstall Uninstall a listed package'
    echo ' update    Update repo, update configs, and link. Also, update git-based packages'
    echo ' config    Update configs and link'
    echo ' link      Link configs'
    echo ' list [-d] List package groups and packages'
    echo ' newscript Create a new script'
    echo ' gits      git status'
    echo ' gitd      git diff'
    echo ' gitp      git pull'
    echo ' help      Show this help'
    exit 1
}

main() {
    isarch || isubuntu || {
            err 'Unsupported distrobution. Use Arch or Ubuntu.'
            exit 1
        }
    CMD="$1"
    [ $# != 0 ] && shift
    case "$CMD" in
        install)
            pkg_install "$@";;
        uninstall)
            pkg_install --uninstall "$@";;
        update)
            update_repo &&
                "$D/scripts/ndots" config &&
                pkg_update_git_pacs;;
        config)
            dots_update &&
                info "Dots configurations updated successfully";;
        link)
            dots_link &&
                info "Dots configurations linked successfully";;
        list)
            list_all "$@";;
        newscript)
            cd "$DOTFILES_DIR/scripts" &&
                new-shell-script "$@";;
        istiny)
            istiny;;
        gits)
            cd "$DOTFILES_DIR" &&
                git status;;
        gitd)
            cd "$DOTFILES_DIR" &&
                git diff;;
        gitp)
            cd "$DOTFILES_DIR" &&
                git pull origin master;;
        'eval')
            eval "$@";;
        '')
            cd "$DOTFILES_DIR" && exec open ;;
        *)
            help;;
    esac
}

main "$@"
