#!/bin/sh

# For normal windows, just kill them the usual way.
# For tmux terminal windows, close magically.

theterm --kill-window
case $? in
    1) # not a tmux session window
        exec xdotool getactivewindow windowkill ;;
    2) # is tmux session but don't know how to exit
    ;;
esac
