#!/bin/sh

# For normal windows, just kill them the usual way.
# For terminal windows, close magically.

CLASS=$(xprop -id "$(xdotool getactivewindow)" |
            sed -En 's/WM_CLASS\(STRING\) = "(.*)"/\1/p' |
            sed 's/".*//')

case "$CLASS" in
    # assuming st is the terminal
    st|st-256color)
        exec theterm --kill-window ;;
    *)
        exec xdotool windowkill "$ID" ;;
esac
