#!/bin/sh

# TODO: move to personal

JAIL="$HOME/Firejail/office2007"
SETUP='office2007'
INSTALLER="/mnt/hdd1/Public/software/non-free-software/Microsoft/office/$SETUP"

LINE='==================================='

info() {
    echo $LINE
    printf '\033[1;34mINFO:\033[0m '
    echo "$@"
    echo $LINE
}

err() {
    {
        echo $LINE
        printf '\033[1m\033[31mERROR:\033[0m '
        echo "$@"
        echo $LINE
    } >&2
}

needed() {
    echo $LINE
    printf '\033[1;33mNEEDED:\033[0m '
    echo "$@"
    echo $LINE
}

install() {
    info 'Not installed! Installing...'
    [ -d "$INSTALLER" ] || {
        err "Installer directory not found at $INSTALLER"
        return 1
    }
    rm -rf "$JAIL" &&
        mkdir -p "$JAIL" &&
        info 'Setting up Wine and installing fonts' &&
        needed 'Once done, set the Windows version to Windows XP' &&
        firejail-my-net office2007 bash -c "
export WINEARCH='win32'
winecfg
winetricks corefonts" &&
        info 'Copying Office...' &&
        cp -r "$INSTALLER" "$JAIL" &&
        info 'Running setup...' &&
        firejail-my office2007 wine "$HOME/$SETUP/setup.exe" &&
        info 'Cleaning...' &&
        rm -rf "$JAIL/$SETUP" &&
        info 'DONE!'
}

main() {
    if [ ! -d "$JAIL" ]; then
        install || exit
    fi

    if [ "$2" ]; then
        rm -rf "$JAIL/tmpdocs/"
        mkdir "$JAIL/tmpdocs/"
        cp "$2" "$JAIL/tmpdocs/"
        ARG="$HOME/tmpdocs/$(basename "$2")"
    fi

    case "$1" in
        w*) APP="WINWORD";;
        e*) APP="EXCEL";;
        p*) APP="POWERPNT";;
    esac

    P="$HOME/.wine/drive_c/Program Files/Microsoft Office/Office12"
    firejail-my office2007 wine "$P/$APP.EXE" "$ARG" #2>/dev/null
}

main "$@"
