#!/bin/sh

# TODO: move to personal

JAIL="$HOME/Firejail/office2010"
SETUP='Microsoft Office Enterprise 2010 Corporate Final (full activated)'
INSTALLER="/mnt/hdd2/GoodStuff2/Things/ms office/$SETUP"
P="$HOME/.wine/drive_c/Program Files/Microsoft Office/Office14"

if [ ! -d "$JAIL" ]; then
    echo 'Not installed! Installing...'
    firejail-my-net office2010 bash -c "
export WINEARCH='win32'
winecfg
winetricks dotnet20 msxml6 corefonts"
    cp -r "$INSTALLER" "$JAIL"
    firejail-my office2010 wine "$HOME/$SETUP/setup.exe"
    rm -rf "$JAIL/$SETUP"
fi

if [ "$2" ]; then
    rm -rf "$JAIL/tmpdocs/"
    mkdir "$JAIL/tmpdocs/"
    cp "$2" "$JAIL/tmpdocs/"
    ARG="$HOME/tmpdocs/$(basename "$2")"
fi

case "$1" in
    w*) APP="WINWORD";;
    e*) APP="EXCEL";;
    p*) APP="POWERPNT";;
esac

firejail-my office2010 wine "$P/$APP.EXE" "$ARG"
