#!/bin/sh

lfsend() {
    if [ "$LFID" != '' ]; then
        while read -r line; do
            lf -remote "send $LFID echo Error: \'$line\'"
        done
    else
        cat 1>&2
    fi
}

openfile() {
    f="$1"
    # if forced from picker
    if [ "$FORCEOPENER" ]; then
        $FORCEOPENER "$f" 2>&1 | lfsend &
    else
        # file name
        case "$f" in
            *.html)
                browser "$f" 2>&1 | lfsend &;;
            *)
                # mime type
                case $(file --mime-type "$(realpath """$f""")" -b) in
                    text/*|*/json|*empty)
                        $EDITOR "$f";;
                    image/*)
                        sxivv "$f" >/dev/null 2>&1 | lfsend &;;
                    video/*)
                        mpv "$f" --loop=inf >/dev/null 2>&1 | lfsend &;;
                    audio/*)
                        music-play "$f";;
                    *)
                        $OPENER "$f" 2>&1 | lfsend &;;
                esac
        esac
    fi
}

pick() {
    MENU='menu-interface -l 20'
    [ "$1" = '--fzf' ] && {
        MENU=fzf
        shift
    }
    echo | mimeopen --ask "$1" 2>/dev/null |
        sed -En 's/.+\)\s+(.+)/\1/p' |
        $MENU |
        sed -En 's/.+\((.+)\)/\1/p'
}

[ "$OPENER" = '' ] && OPENER=xdg-open
FORCEOPENER=''

[ "$1" = '--lfid' ] && {
    LFID="$2"
    shift 2
}

[ "$1" = '--fzf' ] || [ "$1" = '-f' ] && {
    f="$(fzf)"
    [ "$f" != '' ] && openfile "$f"
    exit
}

[ "$1" = '--ask' ] && {
    shift
    # go for fzf if is in terminal
    [ -t 1 ] && FZF=--fzf
    # except if forced
    [ "$1" = '-nw' ] && FZF='' && shift
    FORCEOPENER=$(pick $FZF "$@")
    [ ! "$FORCEOPENER" ] && exit 1
}

[ "$#" = 0 ] && {
    $EDITOR
    exit 0
}

for f in "$@"; do
    # if no such file
    [ ! -e "$f" ] && {
        $EDITOR "$f"
        exit 0
    }
    openfile "$f"
done
