#!/bin/sh

lfsend() {
    if [ "$LFID" != '' ]; then
        while read -r line; do
            lf -remote "send $LFID echo Error: \'$line\'"
        done
    else
        cat 1>&2
    fi
}

openfile() {
    f="$1"
    # file name
    case "$f" in
        *.html)
            browser "$f" >/dev/null 2>/dev/null &;;
        *)
            # mime type
            case $(file --mime-type "$(realpath """$f""")" -b) in
                text/*|*/json|*empty)
                    $EDITOR "$f";;
                image/*)
                    sxivv "$f" >/dev/null 2>&1 | lfsend &;;
                video/*)
                    mpv "$f" --loop=inf >/dev/null 2>&1 | lfsend &;;
                audio/*)
                    music-play "$f";;
                *)
                    $OPENER "$f" 2>&1 | lfsend &;;
            esac
    esac
}

[ "$OPENER" = '' ] && OPENER=xdg-open

[ "$1" = '--lfid' ] && {
    LFID="$2"
    shift 2
}

[ "$1" = '-f' ] && {
    f="$(fzf)"
    [ "$f" != '' ] && openfile "$f"
    exit
}

[ "$#" = 0 ] && {
    $EDITOR
    exit 0
}

for f in "$@"; do
    # if no such file
    [ ! -e "$f" ] && {
        $EDITOR "$f"
        exit 0
    }
    openfile "$f"
done
