#!/bin/bash

lfsend() {
    if [ "$LFID" != '' ]; then
        while read -r line; do
            lf -remote "send $LFID echo Error: \'$line\'"
        done
    else
        cat 1>&2
    fi
}

openfile() {
    f="$1"
    # if directory
    if [ -d "$f" ]; then
        echo "$f" > '/tmp/__opendir'
        return
    fi
    # if forced from picker
    if [ "$FORCEOPENER" ]; then
        opt=--ask
        [ "$DEF" ] && opt=--ask-default
        echo "$FORCEOPENER" |
            mimeopen $opt "$f" >/dev/null 2>&1 | lfsend & disown
    else
        # file name
        case "$f" in
            *.html)
                browser "$f" 2>&1 | lfsend &;;
            *.drawio)
                draw.io "$f" 2>&1 | lfsend &;;
            *)
                # mime type
                case $(file --mime-type "$(realpath """$f""")" -b) in
                    text/*|*/json|*empty)
                        $EDITOR "$f";;
                    image/x-xcf)
                        $OPENER "$f" 2>&1 | lfsend &;;
                    image/*)
                        if [ "$LFID" ]; then
                            sxivv --lf "$LFID" "$f" >/dev/null 2>&1 | lfsend &
                        else
                            sxivv "$f" >/dev/null 2>&1 | lfsend &
                        fi;;
                    video/*)
                        mpv "$f" --loop=inf >/dev/null 2>&1 | lfsend &;;
                    audio/*)
                        music-play "$f";;
                    *)
                        $OPENER "$f" 2>&1 | lfsend &;;
                esac
        esac
    fi
}

pick() {
    MENU='menu-interface -l 20'
    [ "$1" = '--fzf' ] && {
        MENU='fzfp --nopv'
        shift
    }
    echo | mimeopen --ask "$1" 2>/dev/null |
        sed -En 's/\s*(.+\)\s+.+)/\1/p' |
        $MENU |
        sed -En 's/(.+)\).+/\1/p'
}

search() {
    if [ "$1" = '--here' ]; then
        f=$(find "$2" -maxdepth 1 | z)
    elif [ -d "$1" ]; then
        f=$(find "$1" -type f | z)
    else
        f=$(fzfp)
    fi
    [ -e "$f" ] && openfile "$f"
}

[ "$OPENER" = '' ] && OPENER=xdg-open
FORCEOPENER=''

[ "$1" = '--lfid' ] && {
    LFID="$2"
    shift 2
}

FORCEFZF=0
[ "$1" = '--fzf' ] || [ "$1" = '-f' ] && {
    FORCEFZF=1
    shift
}

[ "$#" = 0 ] && {
    search
    exit
}

[ "$1" = . ] && {
    search --here .
    exit
}

# if file specified, all fzf stuff will be passed
[ "$FORCEFZF" = 1 ] && [ -d "$1" ] && {
    search "$1"
    exit
}

[ "$1" = '--ask' ] || [ "$1" = '--ask-default' ] && {
    [ "$1" = '--ask-default' ] && DEF=1
    shift
    # go for fzf if is in terminal
    [ -t 1 ] && FZF=--fzf
    # except if forced
    [ "$1" = '-nw' ] && FZF='' && shift
    FORCEOPENER=$(pick $FZF "$@")
    [ ! "$FORCEOPENER" ] && exit 1
}

[ "$1" = '-e' ] && {
    shift
    $EDITOR "$@"
    exit 0
}

for f in "$@"; do
    # if no such file
    [ ! -e "$f" ] && {
        $EDITOR "$f"
        exit 0
    }
    openfile "$f"
done
