#!/bin/bash
# Quick dirty way to handle generated .tex files from org-mode
# There's certainly a clean solution but I'm a little busy to figure it out now..

F="$1"
F="${F%.*}"
B=$(sed -E -rn 's/\\(bibliography|addbibresource)\{(.+)\}/\2/p' "$F.tex")
[[ "$B" != '' ]] && {
    sed -E -i -r 's/\\(bibliography|addbibresource)\{.+//g' "$F.tex"
    sed -i -r "s/\\\\documentclass(.+)/\\\\documentclass\1\\n\\\\usepackage[backend=biber,sorting=none]{biblatex}\\n\\\\addbibresource\{$B\}/g" "$F.tex"
}

pandoc --bibliography="$BIB" --filter pandoc-citeproc --csl "$HOME/Documents/LaTeX/ieee.csl" "$F.tex" -o "$F.docx"
