#!/bin/sh

for inpdf; do
    echo "Processing file $inpdf..."
    outpdf="$inpdf.images.pdf"

    tmp=".tmp_pdf_$$"
    mkdir "$tmp"

    echo 'Generating images...'
    pdftoppm "$inpdf" "$tmp/i" -jpeg

    echo 'Merging to a PDF...'
    convert "$tmp"/i-*.jpg "$outpdf"

    echo "Created $outpdf"
    rm -rf "$tmp"
    echo
done
