#!/bin/bash
r=0
grepargs=()
ftargs=()
args=($@)
for i in ${!args[@]}; do
    arg=${args[$i]}
    case $arg in
        -r) r=1; args[$i]='';;
        -*) grepargs+=("$arg") args[$i]='';;
        *)  ftargs+=("$arg") args[$i]='';;
    esac
done

function doit {
    f="$1"
    shift
    t="$@"
    #echo "f=$f, t=$t"
    m=$(pdftotext -layout "$f" - 2>/dev/null | grep --color=always $grepargs "$t")
    [[ "$m" != "" ]] && echo -e -n "\033[0;35m$f\033[0;36m:\033[0m " && echo "$m"
}

if [[ "$r" = "1" ]]; then
    T="${ftargs[@]}"
    for F in $(find -name '*.pdf'); do
        doit "$F" "$T"
    done
else
    F="${ftargs[-1]}"
    ftargs[-1]=''
    T="${ftargs[@]}"
    doit "$F" "$T"
fi
