#!/bin/sh

#PDF=pdflatex
PDF=xelatex
BIB=biber
OPT="-interaction=nonstopmode"

DOCX=0
[ "$1" = '-d' ] && {
    DOCX=1
    shift
}

F="$1"
F="${F%.*}"

if [ $DOCX = 1 ]; then
    pandoc --bibliography="$BIB" --filter pandoc-citeproc --csl "$HOME/Documents/LaTeX/ieee.csl" "$F.tex" -o "$F.docx"
else
    if OUT=$($PDF "$OPT" "$F.tex"); then
        if BIBOUT=$($BIB "$F") &&
                ! echo "$BIBOUT" | grep -q 'does not contain any citations!'
        then
            $PDF "$OPT" "$F.tex" >/dev/null 2>/dev/null
        fi
        OUT=$($PDF "$OPT" "$F.tex")
    fi
    ERRS=$(echo "$OUT" |
               grep -A 1 -E '^\! .+')
    WRNS=$(echo "$OUT" |
               grep -A 1 -E 'Warning:' |
               grep -E '^[A-Za-z\(]')
    if [ "$BIBOUT" ]; then
        printf "\e[1;34m>>> BIBLIOGRAPHY (%s):\e[0m\n" "$BIB"
        echo "$BIBOUT"
    fi
    if [ "$ERRS" ]; then
        printf "\e[1;31m>>> ERRORS:\e[0m\n"
        echo "$ERRS"
    fi
    if [ "$WRNS" ]; then
        printf "\e[1;33m>>> WARNINGS:\e[0m\n"
        echo "$WRNS"
    fi
    #echo "$OUT"
    rm -f "$F.aux" "$F.bbl" "$F.bcf" "$F.blg" "$F.log" "$F.out" "$F.run.xml" "$F.aux" "$F.lof" "$F.lot" "$F.toc"
    if [ "$ERRS" ]; then
        exit 1
    fi
fi
