#!/bin/bash
# Quick dirty way to handle generated .tex files from org-mode
# There's certainly a clean solution but I'm a little busy to figure it out now..

PDF=pdflatex
#PDF=xelatex
BIB=biber
OPT="-interaction=nonstopmode"

DOCX=0
[[ "$1" == '-d' ]] && {
    DOCX=1
    shift
}

F="$1"
E="${F##*.}"
F="${F%.*}"

E=org # TODO
[[ "$E" == 'org' ]] && {
    B=$(sed -rn 's/\\(bibliography|addbibresource)\{(.+)\}/\2/p' "$F.tex")
    [[ "$B" != '' ]] && {
        sed -i -r 's/\\(bibliography|addbibresource)\{.+//g' "$F.tex"
        sed -i -r "s@\\\\documentclass(.+)@\\\\documentclass\1\\n\\\\usepackage[backend=biber,sorting=none,style=ieee]{biblatex}\\n\\\\addbibresource\{$B\}@g" "$F.tex"
    }
}

if [[ $DOCX == 1 ]]; then
    pandoc --bibliography="$BIB" --filter pandoc-citeproc --csl "$HOME/Documents/LaTeX/ieee.csl" "$F.tex" -o "$F.docx"
else
    $PDF "$OPT" "$F.tex" &>/dev/null && \
        $BIB "$F" && \
        $PDF "$OPT" "$F.tex" &>/dev/null
    $PDF "$OPT" "$F.tex"
    rm -f "$F.aux" "$F.bbl" "$F.bcf" "$F.blg" "$F.log" "$F.out" "$F.run.xml" "$F.aux" "$F.lof" "$F.lot" "$F.toc" #"$F.tex"
fi
