#!/bin/sh

JAIL=$HOME/Firejail/pol

NET=

list() {
    export QUOTING_STYLE=literal
    ls -1 "$JAIL/.PlayOnLinux/shortcuts"
}

jail_net() {
    exec firejail \
         --private-tmp \
         --blacklist=/mnt \
         --private="$JAIL" "$@"
}

jail() {
    if [ "$NET" ]; then
        jail_net "$@"
    else
        jail_net --net=none "$@"
    fi
}

pol() {
    jail playonlinux "$@"
}

menu() {
    m=menus-face
    command -v $m >/dev/null || m=dmenu
    P=$({ list; echo Manage; } | $m -i -l 20)
    case "$P" in
        Manage) NET=1 pol;;
        '')     return 1;;
        *)      pol --run "$P";;
    esac
}

main() {
    mkdir -p "$JAIL"
    [ "$1" = '--net' ] && NET=1 && shift
    case "$1" in
        '') menu;;
        ls) list;;
        *)
            Q="$1"
            shift
            P=$(list | grep -i "$Q" | head -n1)
            [ "$P" ] && pol --run "$P" "$@"
            ;;
    esac
}

main "$@"
