#!/bin/sh

if [ ! "$1" ]; then
    RES=$(printf "Suspend\nShutdown\nReboot\nLogout\nLock\nHibernate" |
              menu-interface -i -p 'Power options')
else
    RES="$1"
fi

confirm() {
    R=$(printf "Yes\nNo" | menu-interface -p "$RES?" -i \
                                          -sb red -sf black \
                                          -nb black -nf red)
    [ "$R" = "Yes" ]
}

case "$RES" in
    [Ll]ock)      lockscreen ;;
    [Ll]ogout)    confirm && wmctl kill ;;
    [Ss]uspend)   lockscreen && systemctl suspend ;;
    [Hh]ibernate) confirm && lockscreen && systemctl hibernate ;;
    [Rr]eboot)    confirm && systemctl reboot ;;
    [Ss]hutdown)  confirm && systemctl poweroff ;;
    *)         exit 1
esac
