#!/bin/sh

menu() {
    fzf --reverse --height=10 "$@"
}

run() {
    printf '\033[1;32m>>>\033[0m %s\n' "$*" >&2
    "$@"
}

s=$(systemctl list-unit-files --type=service |
        menu --header-lines=1 |
        cut -d ' ' -f1)

run systemctl status --no-pager "$s"
echo

cmd=$({
         echo start
         echo restart
         echo stop
         echo enable
         echo disable
         echo status
     } | menu --prompt="command> ")

[ -n "$cmd" ] &&
    run systemctl "$cmd" "$s"
