#!/bin/sh

# acts like gnome-screenshot
# uses maim, xdotool, xclip

DIR="$HOME/Pictures/Screenshots"

help() {
    BIN=$(basename "$0")
    echo "usage: $BIN [-cwa] [-f FILE]"
    echo '
Options:
  -c        Send the grab directly to the clipboard
  -w        Grab a window instead of the entire screen
  -a        Grab an area of the screen instead of the entire screen
  -f=FILE   Save screenshot directly to this file'
    exit 1
}

C= # clipboard
W= # window
A= # area
F= # file name

while getopts 'cwaf:' arg; do
    case "$arg" in
        c) C=1         ;;
        w) W=1         ;;
        a) A=1         ;;
        f) F="$OPTARG" ;;
        *) help        ;;
    esac
done
shift $((OPTIND-1))

CMD="maim --hidecursor"
if [ "$W" ]; then
    CMD="$CMD -i $(xdotool getactivewindow)"
elif [ "$A" ]; then
    CMD="$CMD -s"
fi

if [ "$C" ]; then
    CMD="$CMD | xclip -selection clipboard -t image/png"
else
    [ "$F" ] || {
        mkdir -p "$DIR"
        F="$DIR/Screenshot from $(date '+%Y-%m-%d %H-%M-%S').png"
    }
    CMD="$CMD '$F'"
fi

[ -z "$A" ] || ndg compositor stop

eval "$CMD"

[ -z "$A" ] || ndg compositor start ||:
