#!/bin/sh

usermodmap=$HOME/.Xmodmap
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

xset r rate 230 50

synclient \
    VertScrollDelta=-500 \
    HorizScrollDelta=-500 \
    TapButton1=1 \
    TapButton2=3 \
    TapButton3=2 \
    MinSpeed=1.5 \
    MaxSpeed=7 \
    AccelFactor=0.1 \
    HorizTwoFingerScroll=1 \
    VertTwoFingerScroll=1 \
    PalmDetect=1
