#!/bin/sh
synclient \
    VertScrollDelta=-55 \
    HorizScrollDelta=-55 \
    TapButton1=1 \
    TapButton2=3 \
    TapButton3=2 \
    MinSpeed=1.5 \
    MaxSpeed=7 \
    AccelFactor=0.1 \
    FingerHigh=1 \
    FingerLow=1
