#!/bin/sh

F="$DOTFILES_DIR/configs/wall.png"
[ "$1" = '-g' ] && echo "$F" && exit
[ "$1" ] && {
    cp "$1" "$F"
    F=$(realpath "$1")
    gsettings set org.gnome.desktop.background picture-uri "file://$F"
}

feh --bg-fill "$F"
