#!/bin/sh

SPEED=255
SENSITIVITY=$SPEED

SYSFS=/sys/devices/platform/i8042/serio1/serio2

# https://www.thinkwiki.org/wiki/UltraNav
# https://www.thinkwiki.org/wiki/How_to_configure_the_TrackPoint
# https://wiki.archlinux.org/title/TrackPoint
# https://wiki.archlinux.org/title/Lenovo_ThinkPad_X230#Touchpad
# https://wiki.archlinux.org/title/Touchpad_Synaptics

C='\033[1m\033[34m' # blue
E='\033[1m\033[31m' # red
R='\033[0m'         # reset

info() {
    printf "${C}INFO:${R} %s\n" "$@"
}

err() {
    printf "${E}ERROR:${R} %s\n" "$@" >&2
}

check_root() {
    if [ "$(id -u)" != 0 ]; then
        err 'Root is needed'
        exit 1
    fi
}

set_trackpoint() {
    info "Setting trackpoint parameters at $SYSFS..."
    check_root
    echo "$SPEED" > "$SYSFS/speed"
    echo "$SENSITIVITY" > "$SYSFS/sensitivity"
}

config_xorg() {
    p=/etc/X11/xorg.conf.d/50-synaptics.conf
    info "Setting Xorg configurations at $p..."
    check_root
    echo '
Section "InputClass"
        Identifier "touchpad"
        MatchProduct "SynPS/2 Synaptics TouchPad"
        # MatchTag "lenovo_x230_all"
        Driver "synaptics"
        # fix touchpad resolution
        Option "VertResolution" "100"
        Option "HorizResolution" "65"
        # disable synaptics driver pointer acceleration
        Option "MinSpeed" "1"
        Option "MaxSpeed" "1"
        # tweak the X-server pointer acceleration
        Option "AccelerationProfile" "2"
        Option "AdaptiveDeceleration" "16"
        Option "ConstantDeceleration" "16"
        Option "VelocityScale" "20"
        Option "AccelerationNumerator" "30"
        Option "AccelerationDenominator" "10"
        Option "AccelerationThreshold" "10"

        Option "VertScrollDelta" "-500"
        Option "HorizScrollDelta" "-500"
        Option "VertTwoFingerScroll" "1"
        Option "HorizTwoFingerScroll" "1"

    # Disable two fingers right mouse click
    Option "TapButton2" "0"
        Option "HorizHysteresis" "100"
        Option "VertHysteresis" "100"
        # fix touchpad scroll speed
        Option "VertScrollDelta" "500"
        Option "HorizScrollDelta" "500"
EndSection
' > "$p"
    info 'Restart Xorg to apply'
}

config_systemd() {
    info 'Setting systemd configuartions...'
    check_root

    p=/etc/systemd/system/trackpoint_parameters.path
    info "Creating $p..."
    echo "
[Unit]
Description=Watch for, and modify, Trackpoint attributes

[Path]
PathExists=$SYSFS/speed

[Install]
WantedBy=default.target
" > "$p"

    p=/etc/systemd/system/trackpoint_parameters.service
    info "Creating $p..."
    echo "
[Unit]
Description=Set TrackPoint attributes

[Service]
ExecStart=$0 trackpoint
" > "$p"

    info 'Running service...'
    systemctl enable trackpoint_parameters.path
    systemctl start trackpoint_parameters.path
}

main() {
    [ $# = 0 ] && return 1
    case "$1" in
        trackpoint)
            set_trackpoint ;;

        init)
            config_xorg
            config_systemd ;;
    esac
}

main "$@"
