#!/bin/sh

# https://wiki.archlinux.org/index.php/System_time

hwsync() {
    echo 'Syncing hardware clock'
    hwclock --systohc
}

auto() {
    command -v ntpd >/dev/null || {
        echo 'Install NTP...'
        pacman -S ntp
    }
    ntpd -qg
}

settime() {
    timedatectl set-time "$1" #"yyyy-MM-dd hh:mm:ss"
}

tui() {
    date=$(dialog --stdout --calendar 'Set current date' 0 0)
    time=$(dialog --stdout --timebox 'Set current time' 0 0)
    d=$(echo "$date" | cut -d/ -f1)
    m=$(echo "$date" | cut -d/ -f2)
    y=$(echo "$date" | cut -d/ -f3)
    echo "$y-$m-$d $time"
}

# To check the current zone defined for the system:
# $ timedatectl status
# To list available zones:
# $ timedatectl list-timezones
# To set your time zone:
# $ sudo timedatectl set-timezone Zone/SubZone

main() {
    if [ "$(id -u)" != 0 ]; then
        echo 'Root is needed'
        exit 1
    fi

    auto
    hwsync
}

main "$@"
