#!/bin/bash
# one line:
# bash -c 'i=$(xdotool getactivewindow); d=$(xprop -id $i | awk \'/_MOTIF_WM_HINTS/ { sub(/,/,"",$5); print $5 }\'); if [ $d = 0 ]; then d=1; else d=0; fi; xprop -id $i -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "0x2, 0x0, 0x$d, 0x0, 0x0"; xdotool windowactivate $i'
i=$(xdotool getactivewindow)
d=$(xprop -id $i | awk '/_MOTIF_WM_HINTS/ { sub(/,/,"",$5); print $5 }')
if [ "$d" = "0" ] && [ "$1" != "u" ]; then
    d=1
else
    d=0
fi
xprop -id $i -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "0x2, 0x0, 0x$d, 0x0, 0x0"
xdotool windowactivate $i
