#!/bin/sh

killall trayer && exit 0

eval "$(xdotool getmouselocation --shell)"
Y=$((Y+15))

trayer --edge top \
	   --align left \
	   --distance "$Y" \
	   --margin "$X" \
	   --widthtype request \
	   --tint 0x000000 \
	   --transparent true \
	   --expand true \
	   --SetDockType false \
	   --alpha 0 &

# trayer doesn't set the location correctly
# for multi-monitor setup
sleep .1
xdotool getactivewindow windowmove "$X" "$Y"
