#!/bin/sh

# https://www.thinkwiki.org/wiki/UltraNav
# https://www.thinkwiki.org/wiki/How_to_configure_the_TrackPoint
# https://wiki.archlinux.org/title/Lenovo_ThinkPad_X230#Touchpad
# https://wiki.archlinux.org/title/Touchpad_Synaptics

# echo 255 > /sys/devices/platform/i8042/serio1/sensitivity
# echo 255 > /sys/devices/platform/i8042/serio1/speed

echo 255 > /sys/devices/platform/i8042/serio1/serio2/speed
echo 255 > /sys/devices/platform/i8042/serio1/serio2/sensitivity

# /etc/X11/xorg.conf.d/50-synaptics.conf
#Section "InputClass"
#        Identifier "touchpad"
#        MatchProduct "SynPS/2 Synaptics TouchPad"
#        # MatchTag "lenovo_x230_all"
#        Driver "synaptics"
#        # fix touchpad resolution
#        Option "VertResolution" "100"
#        Option "HorizResolution" "65"
#        # disable synaptics driver pointer acceleration
#        Option "MinSpeed" "1"
#        Option "MaxSpeed" "1"
#        # tweak the X-server pointer acceleration
#        Option "AccelerationProfile" "2"
#        Option "AdaptiveDeceleration" "16"
#        Option "ConstantDeceleration" "16"
#        Option "VelocityScale" "20"
#        Option "AccelerationNumerator" "30"
#        Option "AccelerationDenominator" "10"
#        Option "AccelerationThreshold" "10"
#	# Disable two fingers right mouse click
#	Option "TapButton2" "0"
#        Option "HorizHysteresis" "100"
#        Option "VertHysteresis" "100"
#        # fix touchpad scroll speed
#        Option "VertScrollDelta" "500"
#        Option "HorizScrollDelta" "500"
#EndSection
#
