#!/bin/sh

list() {
    vboxmanage list vms |
        grep -v '<inaccessible>' |
        sed -En 's/"(.+)" .+/\1/p'
    echo Manage
}

V=$(list | menu-interface)

[ "$V" ] && case "$V" in
    Manage) virtualbox;;
    *) exec vboxmanage startvm "$V";;
esac
