#!/bin/bash

W=$(tput cols)
H=$(tput lines)

if [ "$1" = '--nopv' ]; then
    shift
else
    if [[ "$W" -gt 52 || "$H" -gt 13 ]]; then
        PV=(--preview "lfpv {}" --preview-window)
        if [ "$W" -gt $((H*3)) ]; then
            PV+=(right)
        else
            PV+=(down)
        fi
    fi
fi

fzf "${PV[@]}" --reverse "$@"
