#!/bin/sh

NAME='Zoom-5.6.13632.0328.glibc2.17-x86_64.AppImage'
IMG_URL="https://github.com/probonopd/Zoom.AppImage/releases/download/stable/$NAME"
IMG_DIR="$HOME/.local/share/zoom"
IMG="$IMG_DIR/$NAME"
JAIL="$HOME/Firejail/zoom"

[ -f "$IMG" ] || {
    echo "Downloading AppImage..."
    mkdir -p "$IMG_DIR" &&
        cd "$IMG_DIR" &&
        wget "$IMG_URL"
}

[ -x "$IMG" ] || chmod +x "$IMG"

export GTK_THEME="Adwaita:dark"

mkdir -p "$JAIL"
firejail --appimage --noprofile \
         --private-tmp --blacklist=/mnt \
         --private="$JAIL" \
         "$IMG"
