#!/bin/sh
NAME="__id-pdf-$$"

{
    echo '\documentclass[11pt]{article}'
    echo '\usepackage{graphicx}'
    echo '\pagenumbering{gobble}'
    echo '\begin{document}'
    echo '\begin{center}'
    echo "\includegraphics[width=.7\linewidth]{$1}"
    echo '\end{center}'
    [ -n "$2" ] && {
        echo '\vspace{1cm}'
        echo '\begin{center}'
        echo "\includegraphics[width=.7\linewidth]{$2}"
        echo '\end{center}'
    }
    echo '\end{document}'
} > "${NAME}.tex"

pdflatex "${NAME}.tex" >/dev/null &&
    mv "${NAME}.pdf" "$1.pdf"
rm -f "${NAME}.tex" "${NAME}.aux" "${NAME}.log" "${NAME}.out"
