#!/bin/sh
# TODO: move to personal
export MATLAB_SHELL=/bin/bash
mkdir -p "$HOME/Firejail/matlab"
firejail --quiet --net=none --private-tmp --private="$HOME/Firejail/matlab" "$MATLAB/bin/matlab" "$@"
