#!/bin/sh

# TODO: move to personal

BASE="$HOME/GoodStuff/pdf.js/build/generic/web"
TMP="$BASE/__tmp.pdf"
rm -f "$TMP"
ln -s "$1" "$TMP"

ndots-gui browser --app="file://$BASE/viewer.html?file=__tmp.pdf" >/dev/null
#chromium --app="http://localhost:8888/web/viewer.html?file=__tmp.pdf" >/dev/null
#surf "http://localhost:8888/web/viewer.html?file=__tmp.pdf" >/dev/null
