#!/bin/sh

command -v qrcode >/dev/null && exec qrcode "$@"
command -v npm >/dev/null && {
    echo 'Installing...'
    sudo npm i qrcode &&
        exec qrcode "$@"
}

echo "$@" | curl -F-=\<- qrenco.de
