#!/bin/sh

CMD=~/.config/the-quickcmd.sh

[ -f "$CMD" ] ||
    printf "#!/bin/sh\n\n# TODO: Edit this file\nxdg-open '%s'" "$CMD" \
           > "$CMD"

if [ "$1" = -e ]; then
    xdg-open "$CMD"
else
    exec sh "$CMD"
fi
